import express from 'express';
import structureRoutes from './structureRoutes.js';
import cors from 'cors';
import {readStore,writeStore,readFoundation,writeFoundation,readIntake,writeIntake,readParsing,writeParsing,readChunking,writeChunking,snapshotStructure,audit} from './store.js';
const app=express(); app.use(cors()); app.use(express.json({limit:'10mb'})); app.use('/api',structureRoutes);
const ok=(res:any,data:any)=>res.json(data); const actor=(req:any)=>req.header('x-user-name')||'Dr. Sitaram Soni';
app.get('/api/health',(_,res)=>ok(res,{status:'ok',service:'aris-api',version:'5.0.0-structure-functional',persistence:'atomic-json-single-user',capabilities:{structure:'functional-tree-editor',intake:'metadata-only',parsing:'demo-orchestration',chunking:'prototype-functional',authentication:'not-production'}}));
app.post('/api/auth/login',(req,res)=>{const f=readFoundation(); const {email,password}=req.body||{}; if(!email||!password)return res.status(400).json({error:'Email and password are required'});const user=f.users.find((u:any)=>String(u.email).toLowerCase()===String(email).toLowerCase());if(!user)return res.status(401).json({error:'Invalid credentials'});return res.status(501).json({error:'Password authentication is not configured in this prototype. Use the seeded development session only.'});});
app.get('/api/session',(_,res)=>ok(res,readFoundation().session));
app.get('/api/dashboard',(_,res)=>{const d=readStore(),f=readFoundation();ok(res,{...d.dashboard,cycles:f.cycles,structure:f.structures[0],unitCount:f.units.length,userCount:f.users.length,auditCount:f.auditLogs.length})});
app.get('/api/headings',(_,res)=>ok(res,readStore().headings.sort((a:any,b:any)=>(a.order||0)-(b.order||0))));
app.post('/api/headings',(req,res)=>{const d=readStore(); const h={...req.body,id:req.body.id||`H-${Date.now()}`,order:d.headings.length+1,status:'Draft',coverage:0,locked:false}; d.headings.push(h); writeStore(d); snapshotStructure(`Added heading ${h.title}`,actor(req)); audit(actor(req),'Created heading',h.title,`Heading ${h.id} added`); res.status(201).json(h)});
app.patch('/api/headings/:id',(req,res)=>{const d=readStore(),i=d.headings.findIndex((x:any)=>x.id===req.params.id); if(i<0)return res.status(404).json({error:'Heading not found'}); if(d.headings[i].locked)return res.status(409).json({error:'Published heading is locked'}); d.headings[i]={...d.headings[i],...req.body}; writeStore(d); audit(actor(req),'Updated heading',d.headings[i].title,'Heading properties changed'); ok(res,d.headings[i])});
app.delete('/api/headings/:id',(req,res)=>{const d=readStore(); const h=d.headings.find((x:any)=>x.id===req.params.id); if(!h)return res.status(404).json({error:'Heading not found'}); if(d.headings.some((x:any)=>x.parentId===h.id))return res.status(409).json({error:'Delete or move child headings first'}); d.headings=d.headings.filter((x:any)=>x.id!==h.id); writeStore(d); snapshotStructure(`Deleted heading ${h.title}`,actor(req)); audit(actor(req),'Deleted heading',h.title,'Heading removed'); ok(res,{deleted:true})});
app.post('/api/headings/:id/move',(req,res)=>{const d=readStore(); const sorted=d.headings.sort((a:any,b:any)=>(a.order||0)-(b.order||0)); const i=sorted.findIndex((x:any)=>x.id===req.params.id),dir=req.body.direction; const j=dir==='up'?i-1:i+1; if(i<0||j<0||j>=sorted.length)return ok(res,sorted); [sorted[i].order,sorted[j].order]=[sorted[j].order,sorted[i].order]; writeStore(d); audit(actor(req),'Reordered heading',sorted[j].title,`Moved ${dir}`); ok(res,sorted.sort((a:any,b:any)=>a.order-b.order))});
app.post('/api/structures/:id/validate',(_,res)=>{const hs=readStore().headings; const ids=new Set(hs.map((h:any)=>h.id)); const errors:any[]=[]; const seen=new Set(); hs.forEach((h:any)=>{if(seen.has(h.id))errors.push({type:'duplicate',headingId:h.id,message:'Duplicate heading ID'});seen.add(h.id);if(h.parentId&&!ids.has(h.parentId))errors.push({type:'orphan',headingId:h.id,message:'Parent heading does not exist'});if(!h.title?.trim())errors.push({type:'required',headingId:h.id,message:'Title is required'});if((h.wordLimit||0)<50)errors.push({type:'wordLimit',headingId:h.id,message:'Word limit must be at least 50'});}); ok(res,{valid:errors.length===0,errors,warnings:hs.filter((h:any)=>!(h.contributors||[]).length).map((h:any)=>({headingId:h.id,message:'No contributing unit assigned'})),headingCount:hs.length})});
app.post('/api/structures/:id/publish',(req,res)=>{const d=readStore(),f=readFoundation(); d.headings=d.headings.map((h:any)=>({...h,locked:true,status:'Published'})); writeStore(d); f.structures[0].status='Published';f.structures[0].updatedAt=new Date().toISOString();writeFoundation(f); snapshotStructure('Published and locked structure',actor(req));audit(actor(req),'Published structure',f.structures[0].name,'All headings locked');ok(res,f.structures[0])});
app.post('/api/structures/:id/unlock',(req,res)=>{const d=readStore(),f=readFoundation(); d.headings=d.headings.map((h:any)=>({...h,locked:false,status:'Draft'}));writeStore(d);f.structures[0].status='Draft';writeFoundation(f);audit(actor(req),'Unlocked structure',f.structures[0].name,'Structure returned to draft');ok(res,f.structures[0])});
app.get('/api/structures',(_,res)=>ok(res,readFoundation().structures)); app.get('/api/versions',(_,res)=>ok(res,readFoundation().versions));
app.post('/api/versions',(req,res)=>ok(res,{version:snapshotStructure(req.body.note||'Manual snapshot',actor(req))}));
app.get('/api/cycles',(_,res)=>ok(res,readFoundation().cycles)); app.post('/api/cycles',(req,res)=>{const f=readFoundation(),x={id:`cy-${Date.now()}`,...req.body};f.cycles.push(x);writeFoundation(f);audit(actor(req),'Created cycle',x.name,'New reporting cycle');res.status(201).json(x)});
app.get('/api/units',(_,res)=>ok(res,readFoundation().units));app.post('/api/units',(req,res)=>{const f=readFoundation(),x={id:`unit-${Date.now()}`,contributors:0,status:'Active',...req.body};f.units.push(x);writeFoundation(f);res.status(201).json(x)});
app.get('/api/users',(_,res)=>ok(res,readFoundation().users));app.post('/api/users',(req,res)=>{const f=readFoundation(),x={id:`u-${Date.now()}`,status:'Invited',...req.body};f.users.push(x);writeFoundation(f);res.status(201).json(x)});
app.get('/api/roles',(_,res)=>ok(res,readFoundation().roles)); app.get('/api/audit-logs',(_,res)=>ok(res,readFoundation().auditLogs));
app.get('/api/settings',(_,res)=>ok(res,readFoundation().settings));app.patch('/api/settings',(req,res)=>{const f=readFoundation();f.settings={...f.settings,...req.body};writeFoundation(f);ok(res,f.settings)});

app.get('/api/submissions',(_,res)=>ok(res,readIntake().submissionPackages));
app.get('/api/submissions/:id',(req,res)=>{const i=readIntake();const x=i.submissionPackages.find((s:any)=>s.id===req.params.id);if(!x)return res.status(404).json({error:'Submission not found'});ok(res,{...x,documents:i.documents.filter((d:any)=>d.submissionId===x.id),requirements:i.requirements,comments:i.comments.filter((c:any)=>c.submissionId===x.id)})});
app.post('/api/submissions',(req,res)=>{const i=readIntake();const x={id:`sub-${Date.now()}`,status:'Invited',completeness:0,documents:0,requiredItems:i.requirements.filter((r:any)=>r.mandatory).length,receivedItems:0,comments:0,...req.body};i.submissionPackages.push(x);writeIntake(i);audit(actor(req),'Invited reporting unit',x.unit,`Deadline ${x.deadline}`);res.status(201).json(x)});
app.patch('/api/submissions/:id',(req,res)=>{const i=readIntake(),n=i.submissionPackages.findIndex((s:any)=>s.id===req.params.id);if(n<0)return res.status(404).json({error:'Submission not found'});i.submissionPackages[n]={...i.submissionPackages[n],...req.body};writeIntake(i);audit(actor(req),'Updated submission',i.submissionPackages[n].unit,'Submission workflow changed');ok(res,i.submissionPackages[n])});
app.post('/api/submissions/:id/comments',(req,res)=>{const i=readIntake();const s=i.submissionPackages.find((x:any)=>x.id===req.params.id);if(!s)return res.status(404).json({error:'Submission not found'});const c={id:`c-${Date.now()}`,submissionId:s.id,author:actor(req),message:req.body.message,createdAt:new Date().toISOString()};i.comments.push(c);s.comments=(s.comments||0)+1;writeIntake(i);ok(res,c)});
app.get('/api/documents',(_,res)=>ok(res,readIntake().documents));
app.get('/api/documents/:id',(req,res)=>{const d=readIntake().documents.find((x:any)=>x.id===req.params.id);if(!d)return res.status(404).json({error:'Document not found'});ok(res,d)});
app.post('/api/documents',(req,res)=>{const i=readIntake();const {contentBase64,...meta}=req.body||{};if(!meta.title||!meta.fileName)return res.status(400).json({error:'Title and file are required'});const d={id:`doc-${Date.now()}`,status:'Uploaded',uploadedAt:new Date().toISOString(),uploadedBy:actor(req),pages:meta.pages||0,sizeBytes:meta.sizeBytes||0,validation:{complete:false,issues:['Awaiting validation']},...meta};i.documents.push(d);const s=i.submissionPackages.find((x:any)=>x.id===d.submissionId);if(s){s.documents=(s.documents||0)+1;s.receivedItems=Math.min((s.receivedItems||0)+1,s.requiredItems||99);s.completeness=Math.round((s.receivedItems/Math.max(1,s.requiredItems))*100);if(s.status==='Invited')s.status='In Progress'}writeIntake(i);audit(actor(req),'Uploaded document',d.title,`${d.fileName} (${d.sizeBytes} bytes)`);res.status(201).json(d)});
app.post('/api/documents/:id/validate',(req,res)=>{const i=readIntake(),d=i.documents.find((x:any)=>x.id===req.params.id);if(!d)return res.status(404).json({error:'Document not found'});const issues:string[]=[];if(!d.reportingPeriod)issues.push('Reporting period is missing');if(!d.metadata?.responsibleOfficer)issues.push('Responsible officer is missing');if(!d.metadata?.targetGroup)issues.push('Target group is missing');d.validation={complete:issues.length===0,issues};d.status=issues.length?'Needs Attention':'Validated';writeIntake(i);audit(actor(req),'Validated document',d.title,issues.length?issues.join('; '):'Validation passed');ok(res,d)});
app.post('/api/documents/:id/process',(req,res)=>{const i=readIntake(),d=i.documents.find((x:any)=>x.id===req.params.id);if(!d)return res.status(404).json({error:'Document not found'});if(!d.validation?.complete)return res.status(409).json({error:'Document metadata must be validated before parsing'});d.status='Queued for Parsing';d.processingJob={id:`job-${Date.now()}`,queuedAt:new Date().toISOString(),stage:'parse'};writeIntake(i);audit(actor(req),'Queued document',d.title,'Document sent to parsing queue');ok(res,d)});
app.delete('/api/documents/:id',(req,res)=>{const i=readIntake();const d=i.documents.find((x:any)=>x.id===req.params.id);if(!d)return res.status(404).json({error:'Document not found'});i.documents=i.documents.filter((x:any)=>x.id!==d.id);const s=i.submissionPackages.find((x:any)=>x.id===d.submissionId);if(s){s.documents=Math.max(0,(s.documents||1)-1);s.receivedItems=Math.max(0,(s.receivedItems||1)-1);s.completeness=Math.round((s.receivedItems/Math.max(1,s.requiredItems))*100)}writeIntake(i);audit(actor(req),'Deleted document',d.title,d.fileName);ok(res,{deleted:true})});
app.get('/api/intake/requirements',(_,res)=>ok(res,readIntake().requirements));

app.get('/api/chunks',(_,res)=>ok(res,readStore().chunks)); app.get('/api/mappings/:chunkId',(req,res)=>ok(res,readStore().mappings[req.params.chunkId]??[]));
app.post('/api/ai/chunk',async(req,res)=>{try{const r=await fetch('http://localhost:8001/chunk',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(req.body)});res.status(r.status).json(await r.json())}catch{res.status(503).json({error:'AI service unavailable'})}});
app.post('/api/ai/affinity',async(req,res)=>{try{const r=await fetch('http://localhost:8001/affinity',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(req.body)});res.status(r.status).json(await r.json())}catch{res.status(503).json({error:'AI service unavailable'})}});
// Phase 3: document parsing and normalisation
app.get('/api/parsing/jobs',(_,res)=>ok(res,readParsing().jobs));
app.get('/api/parsing/jobs/:id',(req,res)=>{const p=readParsing();const j=p.jobs.find((x:any)=>x.id===req.params.id);if(!j)return res.status(404).json({error:'Parsing job not found'});ok(res,j)});
app.post('/api/parsing/jobs',(req,res)=>{const p=readParsing(),i=readIntake();const d=i.documents.find((x:any)=>x.id===req.body.documentId);if(!d)return res.status(404).json({error:'Document not found'});const j={id:`job-parse-${Date.now()}`,documentId:d.id,documentTitle:d.title,unit:d.unit,fileName:d.fileName,status:'Queued',progress:0,stage:'queued',createdAt:new Date().toISOString(),startedAt:null,completedAt:null,parser:req.body.parser||'Automatic parser',warnings:0,error:null};p.jobs.unshift(j);d.status='Queued for Parsing';d.processingJob={id:j.id,queuedAt:j.createdAt,stage:'parse'};writeParsing(p);writeIntake(i);audit(actor(req),'Created parsing job',d.title,`Parser: ${j.parser}`);res.status(201).json(j)});
app.post('/api/parsing/jobs/:id/run',(req,res)=>{const p=readParsing();const j=p.jobs.find((x:any)=>x.id===req.params.id);if(!j)return res.status(404).json({error:'Parsing job not found'});j.status='Processing';j.progress=72;j.stage='normalising structure';j.startedAt=j.startedAt||new Date().toISOString();j.error=null;writeParsing(p);audit(actor(req),'Started parsing job',j.documentTitle,j.id);ok(res,j)});
app.post('/api/parsing/jobs/:id/complete',(req,res)=>{const p=readParsing(),i=readIntake();const j=p.jobs.find((x:any)=>x.id===req.params.id);if(!j)return res.status(404).json({error:'Parsing job not found'});j.status='Completed';j.progress=100;j.stage='normalised';j.completedAt=new Date().toISOString();j.error=null;const d=i.documents.find((x:any)=>x.id===j.documentId);if(d)d.status='Parsed';writeParsing(p);writeIntake(i);audit(actor(req),'Completed parsing job',j.documentTitle,'Normalised document ready');ok(res,j)});
app.post('/api/parsing/jobs/:id/retry',(req,res)=>{const p=readParsing();const j=p.jobs.find((x:any)=>x.id===req.params.id);if(!j)return res.status(404).json({error:'Parsing job not found'});j.status='Queued';j.progress=0;j.stage='queued for retry';j.error=null;j.startedAt=null;j.completedAt=null;writeParsing(p);audit(actor(req),'Retried parsing job',j.documentTitle,j.id);ok(res,j)});
app.get('/api/normalized-documents',(_,res)=>ok(res,readParsing().normalizedDocuments));
app.get('/api/normalized-documents/:id',(req,res)=>{const p=readParsing();const n=p.normalizedDocuments.find((x:any)=>x.id===req.params.id||x.documentId===req.params.id);if(!n)return res.status(404).json({error:'Normalised document not found'});ok(res,n)});
app.patch('/api/normalized-documents/:id/blocks/:blockId',(req,res)=>{const p=readParsing();const n=p.normalizedDocuments.find((x:any)=>x.id===req.params.id);if(!n)return res.status(404).json({error:'Normalised document not found'});const b=n.blocks.find((x:any)=>x.id===req.params.blockId);if(!b)return res.status(404).json({error:'Block not found'});Object.assign(b,req.body);n.updatedAt=new Date().toISOString();writeParsing(p);audit(actor(req),'Edited normalised block',n.title,b.id);ok(res,b)});
app.post('/api/normalized-documents/:id/approve',(req,res)=>{const p=readParsing();const n=p.normalizedDocuments.find((x:any)=>x.id===req.params.id);if(!n)return res.status(404).json({error:'Normalised document not found'});n.status='Approved for Chunking';n.approvedAt=new Date().toISOString();n.approvedBy=actor(req);writeParsing(p);audit(actor(req),'Approved normalised document',n.title,'Released to chunking');ok(res,n)});

// Phase 4: intelligent hierarchy-aware chunking
app.get('/api/chunking/profiles',(_,res)=>ok(res,readChunking().profiles));
app.get('/api/chunking/jobs',(_,res)=>ok(res,readChunking().jobs));
app.post('/api/chunking/jobs',(req,res)=>{const c=readChunking(),p=readParsing();const n=p.normalizedDocuments.find((x:any)=>x.id===req.body.documentId||x.documentId===req.body.documentId);if(!n)return res.status(404).json({error:'Normalised document not found'});const profile=c.profiles.find((x:any)=>x.id===req.body.profileId)||c.profiles[0];const j={id:`chunk-job-${Date.now()}`,documentId:n.id,documentTitle:n.title,unit:n.unit,profileId:profile.id,status:'Queued',progress:0,stage:'awaiting worker',strategy:'Hybrid hierarchy + semantic',createdAt:new Date().toISOString(),completedAt:null,chunkCount:0,warnings:0};c.jobs.unshift(j);writeChunking(c);audit(actor(req),'Created chunking job',n.title,`Profile: ${profile.name}`);res.status(201).json(j)});
app.post('/api/chunking/jobs/:id/run',(req,res)=>{const c=readChunking();const j=c.jobs.find((x:any)=>x.id===req.params.id);if(!j)return res.status(404).json({error:'Chunking job not found'});j.status='Processing';j.progress=65;j.stage='semantic boundary detection';writeChunking(c);ok(res,j)});
app.get('/api/chunking/chunks',(_,res)=>ok(res,readChunking().chunks));
app.get('/api/chunking/chunks/:id',(req,res)=>{const c=readChunking().chunks.find((x:any)=>x.id===req.params.id);if(!c)return res.status(404).json({error:'Chunk not found'});ok(res,c)});
app.patch('/api/chunking/chunks/:id',(req,res)=>{const c=readChunking();const x=c.chunks.find((y:any)=>y.id===req.params.id);if(!x)return res.status(404).json({error:'Chunk not found'});c.versions.unshift({id:`cv-${Date.now()}`,chunkId:x.id,version:(x.version||1)+1,createdAt:new Date().toISOString(),createdBy:actor(req),reason:req.body.reason||'Manual review update',text:req.body.text||x.text});Object.assign(x,req.body,{version:(x.version||1)+1,updatedAt:new Date().toISOString()});x.tokens=String(x.text||'').trim().split(/\s+/).filter(Boolean).length;x.preview=(x.preview||x.text||'').slice(0,180);writeChunking(c);audit(actor(req),'Updated evidence chunk',x.id,`Version ${x.version}`);ok(res,x)});
app.get('/api/chunking/chunks/:id/versions',(req,res)=>ok(res,readChunking().versions.filter((x:any)=>x.chunkId===req.params.id).sort((a:any,b:any)=>b.version-a.version)));
app.post('/api/chunking/chunks/:id/split',(req,res)=>{const c=readChunking();const i=c.chunks.findIndex((x:any)=>x.id===req.params.id);if(i<0)return res.status(404).json({error:'Chunk not found'});const src=c.chunks[i],text=String(src.text||src.preview),pos=Math.max(1,Math.min(text.length-1,Number(req.body.position)||Math.floor(text.length/2)));let cut=text.lastIndexOf(' ',pos);if(cut<1)cut=pos;const mk=(suffix:string,t:string)=>({...src,id:`${src.id}-${suffix}-${Date.now()}`,text:t.trim(),preview:t.trim().slice(0,180),tokens:t.trim().split(/\s+/).filter(Boolean).length,status:'Needs Review',version:1,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),lineage:{operation:'split',sourceChunkIds:[src.id]}});const parts=[mk('A',text.slice(0,cut)),mk('B',text.slice(cut))];c.chunks.splice(i,1,...parts);writeChunking(c);audit(actor(req),'Split evidence chunk',src.id,`${parts[0].id}, ${parts[1].id}`);ok(res,parts)});
app.post('/api/chunking/chunks/merge',(req,res)=>{const c=readChunking(),ids=req.body.chunkIds||[];const selected=c.chunks.filter((x:any)=>ids.includes(x.id));if(selected.length<2)return res.status(400).json({error:'Select at least two chunks'});if(new Set(selected.map((x:any)=>x.documentId)).size>1)return res.status(409).json({error:'Only chunks from the same document can be merged'});const first=selected[0],text=selected.map((x:any)=>x.text||x.preview).join('\n\n');const merged={...first,id:`CHK-M-${Date.now()}`,text,preview:text.slice(0,180),tokens:text.split(/\s+/).filter(Boolean).length,status:'Needs Review',version:1,blockIds:[...new Set(selected.flatMap((x:any)=>x.blockIds||[]))],topics:[...new Set(selected.flatMap((x:any)=>x.topics||[]))],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),lineage:{operation:'merge',sourceChunkIds:ids}};c.chunks=c.chunks.filter((x:any)=>!ids.includes(x.id));c.chunks.unshift(merged);writeChunking(c);audit(actor(req),'Merged evidence chunks',merged.id,ids.join(', '));res.status(201).json(merged)});

app.use((err:any,_req:any,res:any,_next:any)=>{console.error(err);res.status(500).json({error:'Internal server error'});});
if(process.env.NODE_ENV!=='test') app.listen(Number(process.env.PORT||4000),()=>console.log(`ARIS API v4.1 running on http://localhost:${process.env.PORT||4000}`)); export default app;
