import {Router} from 'express';
import multer from 'multer';
import {readStructures,writeStructures,readFoundation,audit} from './store.js';

const router=Router();
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:25*1024*1024}});
const now=()=>new Date().toISOString();
const uid=(p:string)=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
const actor=(req:any)=>String(req.header('x-user-id')||req.header('x-actor')||'u1');
const headingTypes=new Set(['title','chapter','heading1','heading2','heading3','heading4','heading5']);
const documentObjectTypes=new Set(['title','chapter']);
const captionParentType:Record<string,string>={tableCaption:'table',imageCaption:'image',textBoxCaption:'textBox'};
const captionTypes=new Set(Object.keys(captionParentType));
const depthOf=(type:string)=>documentObjectTypes.has(type)?0:type.startsWith('heading')?Number(type.slice(7)):null;

function validateTree(data:any, structureId:string){
 const els=data.elements.filter((e:any)=>e.structureId===structureId); const byId=new Map(els.map((e:any)=>[e.id,e])); const errors:any[]=[];
 for(const e of els){
  if(e.parentId&&!byId.has(e.parentId))errors.push({id:e.id,message:'Parent element does not exist'});
  const d=depthOf(e.type); if(d!==null&&d>5)errors.push({id:e.id,message:'Heading hierarchy exceeds five levels'});
  if(e.parentId){const p:any=byId.get(e.parentId); const pd=depthOf(p?.type); const bothDocumentObjects=d===0&&pd===0&&documentObjectTypes.has(e.type)&&documentObjectTypes.has(p?.type); if(d!==null&&pd!==null&&!bothDocumentObjects&&d!==pd+1)errors.push({id:e.id,message:`${e.type} must sit directly below the preceding heading level`});}
  if(captionTypes.has(e.type)){
   const parentElementId=e.properties?.parentElementId; const parent:any=byId.get(parentElementId);
   if(!parent||parent.type!==captionParentType[e.type])errors.push({id:e.id,message:`${e.type} must be attached to its matching parent element`});
   if(parent&&(e.parentId||null)!==(parent.parentId||null))errors.push({id:e.id,message:'Caption must remain at the same tree level as its parent element'});
   if(els.some((x:any)=>x.id!==e.id&&x.type===e.type&&x.properties?.parentElementId===parentElementId))errors.push({id:e.id,message:'Only one caption is allowed for this element'});
  }
 }
 for(const parent of els.filter((e:any)=>['table','image','textBox'].includes(e.type))){
  const captions=els.filter((e:any)=>e.properties?.parentElementId===parent.id);
  if(captions.length>1)errors.push({id:parent.id,message:'Only one caption is allowed for this element'});
 }
 return errors;
}
function descendants(elements:any[],id:string){const out:string[]=[];const walk=(x:string)=>elements.filter(e=>e.parentId===x).forEach(e=>{out.push(e.id);walk(e.id)});walk(id);return out;}
function snapshot(data:any,structureId:string,note:string,userId:string){const s=data.structures.find((x:any)=>x.id===structureId);if(!s)return;s.version=(s.version||0)+1;s.updatedAt=now();data.versions.unshift({id:uid('ver'),structureId,version:s.version,note,createdAt:now(),createdBy:userId,elements:structuredClone(data.elements.filter((e:any)=>e.structureId===structureId))});}
function normalizeOrders(data:any,structureId:string,parentId:string|null){const siblings=data.elements.filter((e:any)=>e.structureId===structureId&&(e.parentId||null)===parentId).sort((a:any,b:any)=>a.order-b.order);const ordered:any[]=[];for(const e of siblings){if(captionTypes.has(e.type))continue;ordered.push(e);const caption=siblings.find((x:any)=>captionTypes.has(x.type)&&x.properties?.parentElementId===e.id);if(caption)ordered.push(caption);}for(const c of siblings.filter((e:any)=>captionTypes.has(e.type)&&!ordered.includes(e)))ordered.push(c);ordered.forEach((e:any,i:number)=>e.order=i);}

router.get('/projects',(req,res)=>{const d=readStructures();const user=actor(req);res.json(d.projects.filter((p:any)=>p.memberIds.includes(user)));});
router.post('/projects',(req,res)=>{const d=readStructures();const name=String(req.body?.name||'').trim();if(!name)return res.status(400).json({error:'Project name is required'});if(name.length>160)return res.status(400).json({error:'Project name must be 160 characters or fewer'});const requestedMembers=Array.isArray(req.body?.memberIds)?req.body.memberIds.filter((x:any)=>typeof x==='string'&&x.trim()):[];const p={id:uid('prj'),name,description:String(req.body?.description||'').trim(),memberIds:Array.from(new Set([actor(req),...requestedMembers])),createdAt:now(),updatedAt:now()};d.projects.push(p);writeStructures(d);audit(actor(req),'Created project',p.name,`Project ${p.id} created`);res.status(201).json(p);});
router.patch('/projects/:id',(req,res)=>{const d=readStructures();const p=d.projects.find((x:any)=>x.id===req.params.id);if(!p)return res.status(404).json({error:'Project not found'});Object.assign(p,req.body,{id:p.id,updatedAt:now()});writeStructures(d);res.json(p);});

router.get('/projects/:projectId/structures',(req,res)=>{const d=readStructures();res.json(d.structures.filter((s:any)=>s.projectId===req.params.projectId));});
router.post('/projects/:projectId/structures',(req,res)=>{const d=readStructures();if(!d.projects.some((p:any)=>p.id===req.params.projectId))return res.status(404).json({error:'Project not found'});const s={id:uid('str'),projectId:req.params.projectId,name:req.body.name?.trim(),description:req.body.description||'',status:'Draft',version:1,createdBy:actor(req),createdAt:now(),updatedAt:now()};if(!s.name)return res.status(400).json({error:'Structure name is required'});d.structures.push(s);writeStructures(d);res.status(201).json(s);});
router.patch('/structures/:id',(req,res)=>{const d=readStructures();const s=d.structures.find((x:any)=>x.id===req.params.id);if(!s)return res.status(404).json({error:'Structure not found'});Object.assign(s,req.body,{id:s.id,projectId:s.projectId,updatedAt:now()});writeStructures(d);res.json(s);});
router.delete('/structures/:id',(req,res)=>{const d=readStructures();const s=d.structures.find((x:any)=>x.id===req.params.id);if(!s)return res.status(404).json({error:'Structure not found'});d.structures=d.structures.filter((x:any)=>x.id!==s.id);d.elements=d.elements.filter((e:any)=>e.structureId!==s.id);d.versions=d.versions.filter((v:any)=>v.structureId!==s.id);writeStructures(d);res.json({deleted:true});});


router.get('/projects/:projectId/reports',(req,res)=>{const d=readStructures();res.json((d.reports||[]).filter((r:any)=>r.projectId===req.params.projectId));});
router.post('/projects/:projectId/reports',(req,res)=>{const d=readStructures();if(!d.projects.some((p:any)=>p.id===req.params.projectId))return res.status(404).json({error:'Project not found'});d.reports=d.reports||[];const structureId=req.body.activeStructureId||null;const structure=structureId?d.structures.find((s:any)=>s.id===structureId&&s.projectId===req.params.projectId):null;if(structureId&&!structure)return res.status(400).json({error:'Active structure must belong to this project'});const r={id:uid('rpt'),projectId:req.params.projectId,name:String(req.body.name||'').trim(),description:req.body.description||'',status:req.body.status||'Draft',activeStructureId:structure?.id||null,activeStructureVersion:structure?.version||null,createdAt:now(),updatedAt:now()};if(!r.name)return res.status(400).json({error:'Report name is required'});d.reports.push(r);writeStructures(d);res.status(201).json(r);});
router.patch('/reports/:id',(req,res)=>{const d=readStructures();d.reports=d.reports||[];const r=d.reports.find((x:any)=>x.id===req.params.id);if(!r)return res.status(404).json({error:'Report not found'});if(req.body.activeStructureId!==undefined){const structure=req.body.activeStructureId?d.structures.find((s:any)=>s.id===req.body.activeStructureId&&s.projectId===r.projectId):null;if(req.body.activeStructureId&&!structure)return res.status(400).json({error:'Active structure must belong to the report project'});r.activeStructureId=structure?.id||null;r.activeStructureVersion=structure?.version||null;}for(const k of ['name','description','status'])if(req.body[k]!==undefined)r[k]=req.body[k];r.updatedAt=now();writeStructures(d);res.json(r);});
router.post('/reports/:id/duplicate',(req,res)=>{const d=readStructures();d.reports=d.reports||[];const src=d.reports.find((x:any)=>x.id===req.params.id);if(!src)return res.status(404).json({error:'Report not found'});const r={...src,id:uid('rpt'),name:String(req.body.name||`${src.name} — Copy`),status:'Draft',createdAt:now(),updatedAt:now()};d.reports.push(r);writeStructures(d);res.status(201).json(r);});
router.delete('/reports/:id',(req,res)=>{const d=readStructures();d.reports=d.reports||[];const before=d.reports.length;d.reports=d.reports.filter((x:any)=>x.id!==req.params.id);if(before===d.reports.length)return res.status(404).json({error:'Report not found'});writeStructures(d);res.json({deleted:true});});
router.post('/reports/:id/apply-structure',(req,res)=>{const d=readStructures();d.reports=d.reports||[];const r=d.reports.find((x:any)=>x.id===req.params.id);if(!r)return res.status(404).json({error:'Report not found'});const structure=d.structures.find((s:any)=>s.id===req.body.structureId&&s.projectId===r.projectId);if(!structure)return res.status(400).json({error:'Structure must belong to the report project'});r.activeStructureId=structure.id;r.activeStructureVersion=structure.version;r.updatedAt=now();writeStructures(d);res.json(r);});
router.post('/projects/:id/duplicate',(req,res)=>{const d=readStructures();const src=d.projects.find((x:any)=>x.id===req.params.id);if(!src)return res.status(404).json({error:'Project not found'});const id=uid('prj');const p={...src,id,name:String(req.body.name||`${src.name} — Copy`),createdAt:now(),updatedAt:now()};d.projects.push(p);d.reports=d.reports||[];const structureMap=new Map<string,string>();d.structures.filter((s:any)=>s.projectId===src.id).forEach((s:any)=>{const sid=uid('str');structureMap.set(s.id,sid);d.structures.push({...s,id:sid,projectId:id,name:s.name,version:1,createdAt:now(),updatedAt:now()});const source=d.elements.filter((e:any)=>e.structureId===s.id);const elementMap=new Map(source.map((e:any)=>[e.id,uid('el')]));source.forEach((e:any)=>d.elements.push({...e,id:elementMap.get(e.id),structureId:sid,parentId:e.parentId?elementMap.get(e.parentId):null}));});d.reports.filter((r:any)=>r.projectId===src.id).forEach((r:any)=>d.reports.push({...r,id:uid('rpt'),projectId:id,activeStructureId:r.activeStructureId?structureMap.get(r.activeStructureId)||null:null,activeStructureVersion:r.activeStructureId?1:null,createdAt:now(),updatedAt:now()}));writeStructures(d);res.status(201).json(p);});
router.delete('/projects/:id',(req,res)=>{const d=readStructures();const p=d.projects.find((x:any)=>x.id===req.params.id);if(!p)return res.status(404).json({error:'Project not found'});const ids=new Set(d.structures.filter((s:any)=>s.projectId===p.id).map((s:any)=>s.id));d.projects=d.projects.filter((x:any)=>x.id!==p.id);d.reports=(d.reports||[]).filter((r:any)=>r.projectId!==p.id);d.structures=d.structures.filter((s:any)=>s.projectId!==p.id);d.elements=d.elements.filter((e:any)=>!ids.has(e.structureId));d.versions=d.versions.filter((v:any)=>!ids.has(v.structureId));writeStructures(d);res.json({deleted:true});});

router.get('/structures/:id/elements',(req,res)=>{const d=readStructures();res.json(d.elements.filter((e:any)=>e.structureId===req.params.id));});
router.post('/structures/:id/elements',(req,res)=>{const d=readStructures();const s=d.structures.find((x:any)=>x.id===req.params.id);if(!s)return res.status(404).json({error:'Structure not found'});let parentId=req.body.parentId||null;const type=req.body.type||'paragraph';let properties=req.body.properties||{};let order=d.elements.filter((e:any)=>e.structureId===s.id&&(e.parentId||null)===parentId).length;if(captionTypes.has(type)){const parentElement=d.elements.find((e:any)=>e.id===properties.parentElementId&&e.structureId===s.id);if(!parentElement||parentElement.type!==captionParentType[type])return res.status(400).json({error:`${type} can only be added after a matching ${captionParentType[type]} element`});if(d.elements.some((e:any)=>e.type===type&&e.properties?.parentElementId===parentElement.id))return res.status(400).json({error:'This element already has a caption'});parentId=parentElement.parentId||null;order=parentElement.order+1;for(const sibling of d.elements.filter((e:any)=>e.structureId===s.id&&(e.parentId||null)===parentId&&e.order>=order))sibling.order++;properties={...properties,parentElementId:parentElement.id};}const e={id:uid('el'),structureId:s.id,parentId,type,title:req.body.title||'',content:req.body.content||'',order,properties};const td=depthOf(e.type);if(td!==null&&td>5)return res.status(400).json({error:'Maximum heading depth is five'});d.elements.push(e);normalizeOrders(d,s.id,parentId);const errors=validateTree(d,s.id);if(errors.length){d.elements=d.elements.filter((x:any)=>x.id!==e.id);normalizeOrders(d,s.id,parentId);return res.status(400).json({error:errors[0].message});}snapshot(d,s.id,`Added ${e.type}`,actor(req));writeStructures(d);res.status(201).json(e);});
router.patch('/elements/:id',(req,res)=>{const d=readStructures();const e=d.elements.find((x:any)=>x.id===req.params.id);if(!e)return res.status(404).json({error:'Element not found'});const before=structuredClone(e);Object.assign(e,req.body,{id:e.id,structureId:e.structureId});const errors=validateTree(d,e.structureId);if(errors.length){Object.assign(e,before);return res.status(400).json({error:errors[0].message});}snapshot(d,e.structureId,`Updated ${e.type}`,actor(req));writeStructures(d);res.json(e);});
router.delete('/elements/:id',(req,res)=>{const d=readStructures();const e=d.elements.find((x:any)=>x.id===req.params.id);if(!e)return res.status(404).json({error:'Element not found'});const attached=d.elements.filter((x:any)=>x.properties?.parentElementId===e.id).map((x:any)=>x.id);const ids=new Set([e.id,...attached,...descendants(d.elements,e.id)]);d.elements=d.elements.filter((x:any)=>!ids.has(x.id));normalizeOrders(d,e.structureId,e.parentId||null);snapshot(d,e.structureId,`Deleted ${ids.size} element(s)`,actor(req));writeStructures(d);res.json({deleted:true,count:ids.size});});
router.post('/elements/:id/move',(req,res)=>{const d=readStructures();const e=d.elements.find((x:any)=>x.id===req.params.id);if(!e)return res.status(404).json({error:'Element not found'});if(captionTypes.has(e.type))return res.status(400).json({error:'Captions are fixed immediately after their parent element'});const targetParentId=req.body.parentId||null;if(targetParentId===e.id||descendants(d.elements,e.id).includes(targetParentId))return res.status(400).json({error:'An element cannot be moved into itself or its descendants'});const oldParent=e.parentId||null;const attachedCaption=d.elements.find((x:any)=>captionTypes.has(x.type)&&x.properties?.parentElementId===e.id);const oldCaptionParent=attachedCaption?.parentId||null;e.parentId=targetParentId;if(attachedCaption)attachedCaption.parentId=targetParentId;const siblings=d.elements.filter((x:any)=>x.structureId===e.structureId&&(x.parentId||null)===targetParentId&&x.id!==e.id&&x.id!==attachedCaption?.id).sort((a:any,b:any)=>a.order-b.order);const pos=Math.max(0,Math.min(Number(req.body.index??siblings.length),siblings.length));siblings.splice(pos,0,e);if(attachedCaption)siblings.splice(pos+1,0,attachedCaption);siblings.forEach((x:any,i:number)=>x.order=i);normalizeOrders(d,e.structureId,oldParent);normalizeOrders(d,e.structureId,targetParentId);const errors=validateTree(d,e.structureId);if(errors.length){e.parentId=oldParent;if(attachedCaption)attachedCaption.parentId=oldCaptionParent;normalizeOrders(d,e.structureId,oldParent);normalizeOrders(d,e.structureId,targetParentId);return res.status(400).json({error:errors[0].message});}snapshot(d,e.structureId,'Reordered report structure',actor(req));writeStructures(d);res.json(e);});
router.post('/structures/:id/duplicate',(req,res)=>{const d=readStructures();const src=d.structures.find((x:any)=>x.id===req.params.id);if(!src)return res.status(404).json({error:'Structure not found'});const id=uid('str');const s={...src,id,name:req.body.name||`${src.name} — Copy`,status:'Draft',version:1,createdAt:now(),updatedAt:now(),createdBy:actor(req)};d.structures.push(s);const source=d.elements.filter((e:any)=>e.structureId===src.id);const map=new Map(source.map((e:any)=>[e.id,uid('el')]));source.forEach((e:any)=>d.elements.push({...e,id:map.get(e.id),structureId:id,parentId:e.parentId?map.get(e.parentId):null}));writeStructures(d);res.status(201).json(s);});
router.get('/structures/:id/versions',(req,res)=>{const d=readStructures();res.json(d.versions.filter((v:any)=>v.structureId===req.params.id).map(({elements,...v}:any)=>v));});
router.post('/structures/:id/restore/:versionId',(req,res)=>{const d=readStructures();const v=d.versions.find((x:any)=>x.id===req.params.versionId&&x.structureId===req.params.id);if(!v)return res.status(404).json({error:'Version not found'});d.elements=d.elements.filter((e:any)=>e.structureId!==req.params.id).concat(structuredClone(v.elements));snapshot(d,req.params.id,`Restored version ${v.version}`,actor(req));writeStructures(d);res.json({restored:true});});

router.post('/structures/:id/import-text',(req,res)=>{const text=String(req.body.text||'');if(!text.trim())return res.status(400).json({error:'Paste text is empty'});const blocks=parsePlainText(text);res.json({blocks});});
router.post('/structures/:id/import-file',upload.single('file'),async(req,res)=>{if(!req.file)return res.status(400).json({error:'File is required'});try{const r=await fetch(`${process.env.AI_SERVICE_URL||'http://127.0.0.1:8001'}/parse`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({file_name:req.file.originalname,content_base64:req.file.buffer.toString('base64')})});const body:any=await r.json();if(!r.ok)return res.status(r.status).json({error:body.detail||'Import parser failed'});res.json({fileName:req.file.originalname,blocks:body.blocks,warnings:body.warnings||[]});}catch(err:any){res.status(502).json({error:`Document parser unavailable: ${err.message}`});}});
router.post('/structures/:id/apply-import',(req,res)=>{const d=readStructures();const s=d.structures.find((x:any)=>x.id===req.params.id);if(!s)return res.status(404).json({error:'Structure not found'});const mode=req.body.mode==='replace'?'replace':'append';if(mode==='replace')d.elements=d.elements.filter((e:any)=>e.structureId!==s.id);const created=blocksToElements(req.body.blocks||[],s.id,d.elements);d.elements.push(...created);snapshot(d,s.id,`Imported ${created.length} elements`,actor(req));writeStructures(d);res.json({created:created.length,elements:created});});

function parsePlainText(text:string){return text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean).map((line,i)=>{let m=line.match(/^(#{1,5})\s+(.+)/);if(m)return {type:'heading',level:m[1].length,text:m[2],order:i};m=line.match(/^(\d+(?:\.\d+){0,4})[.)]?\s+(.+)/);if(m)return {type:'heading',level:Math.min(5,m[1].split('.').length),text:m[2],order:i};if(/^[-•*]\s+/.test(line))return {type:'list',listStyle:'bullet',items:[line.replace(/^[-•*]\s+/,'')],order:i};if(/^\d+[.)]\s+/.test(line))return {type:'list',listStyle:'number',items:[line.replace(/^\d+[.)]\s+/, '')],order:i};return {type:i===0&&line.length<120?'title':'paragraph',text:line,order:i};});}
function blocksToElements(blocks:any[],structureId:string,existing:any[]){const out:any[]=[];const stack:(string|null)[]=[null,null,null,null,null,null];let lastHeading:string|null=null;let rootCount=existing.filter(e=>e.structureId===structureId&&!e.parentId).length;for(const b of blocks){let type='paragraph',parentId=lastHeading,title='',content='';if(b.type==='title'){type='title';title=b.text||'Untitled';parentId=null;}else if(b.type==='heading'){const level=Math.max(1,Math.min(5,Number(b.level||1)));type=`heading${level}`;title=b.text||'Untitled heading';parentId=level===1?null:stack[level-1]||null;const id=uid('el');stack[level]=id;for(let j=level+1;j<=5;j++)stack[j]=null;lastHeading=id;out.push({id,structureId,parentId,type,title,content:'',order:parentId?out.filter(e=>e.parentId===parentId).length:rootCount++,properties:defaultProps()});continue;}else if(b.type==='list'){type=b.listStyle==='number'?'numberedList':'bullets';content=(b.items||[]).join('\n');}else if(b.type==='table'){type='table';title=b.caption||'Table';content=JSON.stringify({columns:b.columns||[],rows:b.rows||[]});}else if(b.type==='image'){type='image';title=b.caption||b.fileName||'Image';content=b.dataUrl||'';}else if(b.type==='textBox'){type='textBox';content=b.text||'';}else{content=b.text||'';}const id=uid('el');out.push({id,structureId,parentId,type,title,content,order:parentId?out.filter(e=>e.parentId===parentId).length:rootCount++,properties:headingTypes.has(type)?defaultProps():{}});}return out;}
function defaultProps(){return {owner:'',reviewer:'',wordLimit:600,description:'',include:[],exclude:[],evidenceTypes:[],expectedMetrics:[],contributors:[]};}
export default router;
