import{useEffect,useMemo,useState}from'react';import PageHeader from'../components/PageHeader';import{Card,Badge,Button,Modal}from'../components/UI';import{getJson,sendJson}from'../api';import type{Chunk,ChunkJob,ChunkProfile,ChunkVersion,NormalizedDocument}from'../types';
type Tab='workspace'|'jobs'|'profiles';
const tone=(s:string)=>s==='Approved'||s==='Completed'?'green':s==='Needs Review'||s==='Processing'?'orange':s==='Pending'||s==='Queued'?'blue':'red';
export default function Chunks(){
 const[chunks,setChunks]=useState<Chunk[]>([]),[jobs,setJobs]=useState<ChunkJob[]>([]),[profiles,setProfiles]=useState<ChunkProfile[]>([]),[docs,setDocs]=useState<NormalizedDocument[]>([]),[selected,setSelected]=useState<Chunk|null>(null),[versions,setVersions]=useState<ChunkVersion[]>([]),[tab,setTab]=useState<Tab>('workspace'),[query,setQuery]=useState(''),[status,setStatus]=useState('All'),[notice,setNotice]=useState(''),[showNew,setShowNew]=useState(false),[splitAt,setSplitAt]=useState(0),[mergeId,setMergeId]=useState('');
 const load=()=>Promise.all([getJson<Chunk[]>('/chunking/chunks'),getJson<ChunkJob[]>('/chunking/jobs'),getJson<ChunkProfile[]>('/chunking/profiles'),getJson<NormalizedDocument[]>('/normalized-documents')]).then(([c,j,p,d])=>{setChunks(c);setJobs(j);setProfiles(p);setDocs(d)});useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>chunks.filter(c=>(status==='All'||c.status===status)&&(`${c.id} ${c.preview} ${c.sourceSection} ${c.unit}`.toLowerCase().includes(query.toLowerCase()))),[chunks,status,query]);
 const open=async(c:Chunk)=>{setSelected(c);setSplitAt(Math.max(1,Math.floor((c.text||c.preview).length/2)));setVersions(await getJson<ChunkVersion[]>(`/chunking/chunks/${c.id}/versions`))};
 const patch=async(body:Partial<Chunk>)=>{if(!selected)return;const c=await sendJson<Chunk>(`/chunking/chunks/${selected.id}`,'PATCH',body);setSelected(c);setChunks(x=>x.map(y=>y.id===c.id?c:y));setNotice('Chunk saved with a new version')};
 const split=async()=>{if(!selected)return;await sendJson(`/chunking/chunks/${selected.id}/split`,'POST',{position:splitAt});setSelected(null);setNotice('Chunk split into two reviewable evidence units');load()};
 const merge=async()=>{if(!selected||!mergeId)return;await sendJson('/chunking/chunks/merge','POST',{chunkIds:[selected.id,mergeId]});setSelected(null);setMergeId('');setNotice('Chunks merged with lineage retained');load()};
 const createJob=async(e:any)=>{e.preventDefault();const f=new FormData(e.currentTarget);await sendJson('/chunking/jobs','POST',{documentId:f.get('documentId'),profileId:f.get('profileId')});setShowNew(false);setNotice('Chunking job created');load()};
 return <><PageHeader title="Intelligent Chunking" subtitle="Create hierarchy-aware, semantic, event, topic, list and table evidence units"/>{notice&&<div className="notice success">{notice}</div>}
 <div className="metricGrid four"><Card><strong>{chunks.length}</strong><span>Generated chunks</span></Card><Card><strong>{chunks.filter(x=>x.status==='Approved').length}</strong><span>Approved</span></Card><Card><strong>{chunks.filter(x=>x.status!=='Approved').length}</strong><span>Awaiting review</span></Card><Card><strong>{Math.round(chunks.reduce((a,c)=>a+c.tokens,0)/Math.max(1,chunks.length))}</strong><span>Average tokens</span></Card></div>
 <div className="tabbar"><button className={tab==='workspace'?'active':''} onClick={()=>setTab('workspace')}>Chunk workspace</button><button className={tab==='jobs'?'active':''} onClick={()=>setTab('jobs')}>Processing jobs</button><button className={tab==='profiles'?'active':''} onClick={()=>setTab('profiles')}>Chunking profiles</button></div>
 {tab==='workspace'&&<><Card><div className="toolbar"><input placeholder="Search chunks, source sections or units" value={query} onChange={e=>setQuery(e.target.value)}/><select value={status} onChange={e=>setStatus(e.target.value)}><option>All</option><option>Approved</option><option>Needs Review</option><option>Pending</option></select><Button onClick={()=>setShowNew(true)}>New chunking job</Button></div></Card><Card><table><thead><tr><th>Chunk</th><th>Evidence preview</th><th>Inherited hierarchy</th><th>Type</th><th>Tokens</th><th>Quality</th><th>Status</th><th></th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td><b>{x.id}</b><small className="cellSub">v{x.version||1} · {x.unit}</small></td><td className="wideCell">{x.preview}</td><td>{x.headingPath?.map(h=><span className="crumb" key={h}>{h}</span>)||x.sourceSection}</td><td><Badge tone="blue">{x.type||'topic'}</Badge></td><td>{x.tokens}</td><td>{x.quality||'-'}%</td><td><Badge tone={tone(x.status)}>{x.status}</Badge></td><td><Button variant="secondary" onClick={()=>open(x)}>Review</Button></td></tr>)}</tbody></table></Card></>}
 {tab==='jobs'&&<Card><div className="cardTitle"><div><h3>Chunking queue</h3><p>Controlled processing from approved normalised documents</p></div><Button onClick={()=>setShowNew(true)}>Create job</Button></div><table><thead><tr><th>Document</th><th>Unit</th><th>Strategy</th><th>Stage</th><th>Progress</th><th>Chunks</th><th>Status</th></tr></thead><tbody>{jobs.map(j=><tr key={j.id}><td><b>{j.documentTitle}</b><small className="cellSub">{j.id}</small></td><td>{j.unit}</td><td>{j.strategy}</td><td>{j.stage}</td><td><div className="progress"><i style={{width:`${j.progress}%`}}/></div><small>{j.progress}%</small></td><td>{j.chunkCount}</td><td><Badge tone={tone(j.status)}>{j.status}</Badge></td></tr>)}</tbody></table></Card>}
 {tab==='profiles'&&<div className="profileGrid">{profiles.map(p=><Card key={p.id}><div className="cardTitle"><div><h3>{p.name}</h3><p>{p.status}</p></div><Badge tone={p.status==='Default'?'green':'blue'}>{p.status}</Badge></div><div className="profileStats"><span><b>{p.targetTokens}</b> target</span><span><b>{p.maxTokens}</b> maximum</span><span><b>{p.overlapTokens}</b> overlap</span></div><div className="checkList"><span>✓ Heading inheritance</span><span>✓ Lists preserved</span><span>✓ Tables preserved</span><span>{p.eventAware?'✓':'—'} Event-aware boundaries</span><span>{p.topicAware?'✓':'—'} Topic-aware boundaries</span></div></Card>)}</div>}
 {showNew&&<Modal title="Create chunking job" onClose={()=>setShowNew(false)}><form onSubmit={createJob}><label>Approved normalised document<select name="documentId" required>{docs.map(d=><option value={d.id} key={d.id}>{d.title} — {d.status}</option>)}</select></label><label>Chunking profile<select name="profileId" required>{profiles.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><div className="notice">The job preserves source blocks, inherited headings, pages, tables and lists. Every generated chunk remains traceable to its source.</div><div className="modalActions"><Button variant="secondary" type="button" onClick={()=>setShowNew(false)}>Cancel</Button><Button type="submit">Create job</Button></div></form></Modal>}
 {selected&&<Modal title={`Review ${selected.id}`} onClose={()=>setSelected(null)}><div className="reviewGrid"><div><label>Chunk content<textarea rows={10} value={selected.text||selected.preview} onChange={e=>setSelected({...selected,text:e.target.value,preview:e.target.value.slice(0,150)})}/></label><div className="twoCol"><label>Evidence type<select value={selected.type||'topic'} onChange={e=>setSelected({...selected,type:e.target.value})}><option>event</option><option>topic</option><option>metric</option><option>list</option><option>table</option><option>policy</option></select></label><label>Status<select value={selected.status} onChange={e=>setSelected({...selected,status:e.target.value})}><option>Pending</option><option>Needs Review</option><option>Approved</option><option>Rejected</option></select></label></div><label>Topics<input value={selected.topics.join(', ')} onChange={e=>setSelected({...selected,topics:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})}/></label></div><aside className="metaPanel"><b>Inherited context</b><p><span>Document</span>{selected.documentTitle}</p><p><span>Unit</span>{selected.unit}</p><p><span>Section</span>{selected.sourceSection}</p><p><span>Source blocks</span>{selected.blockIds?.join(', ')}</p><p><span>Tokens</span>{selected.tokens}</p><p><span>Quality</span>{selected.quality}%</p><b>Version history</b>{versions.map(v=><div className="versionMini" key={v.id}><strong>v{v.version}</strong><span>{v.createdBy}</span><small>{v.reason}</small></div>)}</aside></div><div className="operationPanel"><div><b>Split at character position</b><input type="number" value={splitAt} onChange={e=>setSplitAt(Number(e.target.value))}/><Button variant="secondary" onClick={split}>Split</Button></div><div><b>Merge with adjacent chunk</b><select value={mergeId} onChange={e=>setMergeId(e.target.value)}><option value="">Select chunk</option>{chunks.filter(c=>c.id!==selected.id&&c.documentId===selected.documentId).map(c=><option value={c.id} key={c.id}>{c.id} — {c.sourceSection}</option>)}</select><Button variant="secondary" onClick={merge}>Merge</Button></div></div><div className="modalActions"><Button variant="secondary" onClick={()=>setSelected(null)}>Close</Button><Button onClick={()=>patch({text:selected.text,preview:selected.preview,type:selected.type,status:selected.status,topics:selected.topics})}>Save version</Button><Button onClick={()=>patch({status:'Approved'})}>Approve</Button></div></Modal>}</>}
