import {useEffect,useMemo,useState} from 'react';
import {createPortal} from 'react-dom';
import {ChevronDown,ChevronRight,Copy,FileUp,FolderPlus,GripVertical,Image as ImageIcon,Plus,Save,Trash2,Upload,Users,MoreVertical,PanelRightClose,PanelRightOpen} from 'lucide-react';
import PageHeader from '../components/PageHeader';import{Badge,Button,Card,ConfirmDialog,Modal}from'../components/UI';import{deleteJson,getJson,patchJson,postJson}from'../api';import type{Project,Report,ReportStructure,StructureElement,StructureElementType}from'../types';
const TYPES:{value:StructureElementType;label:string}[]=[['title','Title'],['chapter','Chapter'],['heading1','Heading 1'],['heading2','Heading 2'],['heading3','Heading 3'],['heading4','Heading 4'],['heading5','Heading 5'],['paragraph','Paragraph'],['bullets','Bullet list'],['numberedList','Numbered list'],['table','Table'],['tableCaption','Table Caption'],['textBox','Text box'],['textBoxCaption','Text Box Caption'],['image','Image'],['imageCaption','Image Caption']].map(([value,label])=>({value:value as StructureElementType,label}));
const CAPTION_PARENT:Partial<Record<StructureElementType,StructureElementType>>={tableCaption:'table',imageCaption:'image',textBoxCaption:'textBox'};const captionType=(t:string)=>t in CAPTION_PARENT;
const numberedHeading=(t:string)=>/^heading[1-5]$/.test(t);const documentObject=(t:string)=>t==='title'||t==='chapter';const heading=(t:string)=>documentObject(t)||numberedHeading(t);const depth=(t:string)=>documentObject(t)?0:t.startsWith('heading')?Number(t.slice(7)):null;
type DropHint={kind:'before'|'inside'|'after'|'root'|'invalid';targetId?:string;parentId:string|null;index:number;label:string};
const freeElement=(t:string)=>!heading(t)&&!captionType(t);
const canParent=(childType:string,parentType:string|null)=>{const childDepth=depth(childType);if(captionType(childType))return false;if(freeElement(childType))return parentType===null||heading(parentType);if(childType==='title')return parentType===null;if(childType==='chapter')return parentType===null||parentType==='title';if(childDepth===1)return parentType===null||documentObject(parentType||'');if(childDepth&&childDepth>1)return depth(parentType||'')===childDepth-1;return false};
export default function Structure(){
 const[projects,setProjects]=useState<Project[]>([]),[projectId,setProjectId]=useState(''),[reports,setReports]=useState<Report[]>([]),[reportId,setReportId]=useState(''),[structures,setStructures]=useState<ReportStructure[]>([]),[structureId,setStructureId]=useState(''),[elements,setElements]=useState<StructureElement[]>([]),[selectedId,setSelectedId]=useState(''),[expanded,setExpanded]=useState<Set<string>>(new Set()),[notice,setNotice]=useState(''),[newProject,setNewProject]=useState(false),[newReport,setNewReport]=useState(false),[newStructure,setNewStructure]=useState(false),[importOpen,setImportOpen]=useState(false),[confirmAction,setConfirmAction]=useState<null|{kind:'element'|'project'|'report'|'structure';title:string;message:string;name:string;id?:string}>(null),[deleting,setDeleting]=useState(false),[contextMenu,setContextMenu]=useState<null|{id:string;x:number;y:number}>(null),[inspectorVisible,setInspectorVisible]=useState(true),[contentExpanded,setContentExpanded]=useState<Set<string>>(new Set()),[draggedId,setDraggedId]=useState(''),[dropHint,setDropHint]=useState<DropHint|null>(null);
 const loadProjects=async()=>{const p=await getJson<Project[]>('/projects');setProjects(p);if(!projectId&&p[0])setProjectId(p[0].id)};
 const loadReports=async(pid=projectId)=>{if(!pid){setReports([]);setReportId('');return}const r=await getJson<Report[]>(`/projects/${pid}/reports`);setReports(r);if(!r.some(x=>x.id===reportId))setReportId(r[0]?.id||'')};
 const loadStructures=async(pid=projectId)=>{if(!pid)return;const s=await getJson<ReportStructure[]>(`/projects/${pid}/structures`);setStructures(s);if(!s.some(x=>x.id===structureId))setStructureId(s[0]?.id||'')};
 const loadElements=async(sid=structureId)=>{if(!sid){setElements([]);return}const e=await getJson<StructureElement[]>(`/structures/${sid}/elements`);setElements(e);setExpanded(new Set(e.filter(x=>e.some(y=>y.parentId===x.id)).map(x=>x.id)));if(selectedId&&!e.some(x=>x.id===selectedId))setSelectedId('')};
 useEffect(()=>{loadProjects()},[]);useEffect(()=>{loadReports(projectId);loadStructures(projectId)},[projectId]);useEffect(()=>{loadElements(structureId)},[structureId]);useEffect(()=>{const r=reports.find(x=>x.id===reportId);if(r?.activeStructureId&&structures.some(s=>s.id===r.activeStructureId))setStructureId(r.activeStructureId)},[reportId]);
 const selected=elements.find(e=>e.id===selectedId)||null;const children=useMemo(()=>{const m=new Map<string|null,StructureElement[]>();elements.forEach(e=>{const k=e.parentId||null;m.set(k,[...(m.get(k)||[]),e])});m.forEach(a=>a.sort((x,y)=>x.order-y.order));return m},[elements]);
 const numbering=useMemo(()=>{const out=new Map<string,string>();const walk=(pid:string|null,prefix:number[]=[])=>{let n=0;for(const e of children.get(pid)||[]){if(documentObject(e.type)){walk(e.id,[]);continue}if(numberedHeading(e.type)){n++;const nums=[...prefix,n];out.set(e.id,nums.join('.'));walk(e.id,nums)}else walk(e.id,prefix)}};walk(null);return out},[children]);
 const add=async(type:StructureElementType,placement?:{parentId:string|null;index:number;captionForId?:string})=>{if(!structureId){setNotice('Select a structure before adding elements.');return}let finalParent=placement?.parentId??(selected?.parentId||null);let targetIndex=placement?.index??(selected?Math.max(0,(children.get(selected.parentId||null)||[]).findIndex(x=>x.id===selected.id)+1):(children.get(null)||[]).length);let properties:any={};if(captionType(type)){const requiredParent=CAPTION_PARENT[type];const parentElement=placement?.captionForId?elements.find(e=>e.id===placement.captionForId):selected;if(!parentElement||parentElement.type!==requiredParent){setNotice(`${TYPES.find(x=>x.value===type)?.label} can only be added after a selected ${TYPES.find(x=>x.value===requiredParent)?.label}.`);return}if(elements.some(e=>e.type===type&&e.properties?.parentElementId===parentElement.id)){setNotice(`${TYPES.find(x=>x.value===type)?.label} already exists for this element.`);return}finalParent=parentElement.parentId||null;targetIndex=Math.max(0,(children.get(finalParent)||[]).findIndex(x=>x.id===parentElement.id)+1);properties={parentElementId:parentElement.id}}else if(heading(type)){const d=depth(type)!;if(d===0){if(type==='title'){finalParent=null}else if(selected&&documentObject(selected.type)){finalParent=selected.id;targetIndex=(children.get(selected.id)||[]).length}else if(finalParent&&!documentObject(elements.find(e=>e.id===finalParent)?.type||'')){finalParent=null}}else if(d===1){if(selected&&depth(selected.type)===0){finalParent=selected.id;targetIndex=(children.get(selected.id)||[]).length}else if(finalParent&&depth(elements.find(e=>e.id===finalParent)?.type||'')!==0){finalParent=null}}else{const selectedDepth=selected?depth(selected.type):null;if(selected&&selectedDepth===d-1){finalParent=selected.id;targetIndex=(children.get(selected.id)||[]).length}else if(!finalParent||depth(elements.find(e=>e.id===finalParent)?.type||'')!==d-1){setNotice(`Heading ${d} must be added under Heading ${d-1}. Select the intended parent first.`);return}}}else if(selected&&heading(selected.type)){finalParent=selected.id;targetIndex=(children.get(selected.id)||[]).length}const title=captionType(type)?`New ${TYPES.find(x=>x.value===type)?.label}`:heading(type)||type==='title'?`New ${TYPES.find(x=>x.value===type)?.label}`:'';try{const e=await postJson<StructureElement>(`/structures/${structureId}/elements`,{type,parentId:finalParent,title,content:'',properties:heading(type)?{owner:'',reviewer:'',wordLimit:600,description:'',include:[],exclude:[],evidenceTypes:[],expectedMetrics:[],contributors:[]}:properties});if(!captionType(type))await postJson(`/elements/${e.id}/move`,{parentId:finalParent,index:targetIndex});await loadElements();setSelectedId(e.id);if(finalParent)setExpanded(x=>new Set(x).add(finalParent));setNotice(`${TYPES.find(x=>x.value===type)?.label} added at the selected tree position.`)}catch(e:any){setNotice(e?.message||'Unable to add element')}};
 const update=async(patch:Partial<StructureElement>)=>{if(!selected)return;const e=await patchJson<StructureElement>(`/elements/${selected.id}`,patch);setElements(a=>a.map(x=>x.id===e.id?e:x));setNotice('Saved')};
 const remove=(element:StructureElement|null=selected)=>{if(!element)return;setSelectedId(element.id);setConfirmAction({kind:'element',title:'Delete structure element',message:'This element and every child element beneath it will be permanently removed.',name:element.title||preview(element),id:element.id})};
 const changeType=async(element:StructureElement,type:StructureElementType)=>{try{const updated=await patchJson<StructureElement>(`/elements/${element.id}`,{type});setElements(list=>list.map(x=>x.id===updated.id?updated:x));setSelectedId(updated.id);setContextMenu(null);setNotice(`Element changed to ${TYPES.find(x=>x.value===type)?.label}.`)}catch(e:any){setNotice(e?.message||'Unable to change element type')}};
 const onDrop=async(ev:React.DragEvent,targetParent:string|null,index:number)=>{ev.preventDefault();const id=ev.dataTransfer.getData('text/aris-element')||draggedId;if(!id)return;setDropHint(null);setDraggedId('');try{await postJson(`/elements/${id}/move`,{parentId:targetParent,index});await loadElements();setSelectedId(id);setNotice('Element moved to the highlighted position.')}catch(e:any){setNotice(e.message)}};
 const createProject=async(name:string,description='')=>{const p=await postJson<Project>('/projects',{name,description});setProjects(current=>[...current.filter(x=>x.id!==p.id),p]);setProjectId(p.id);setReports([]);setReportId('');setStructures([]);setStructureId('');setElements([]);setSelectedId('');setNewProject(false);setNotice(`Project “${p.name}” created successfully`)};
 const createReport=async(name:string,description='')=>{const r=await postJson<Report>(`/projects/${projectId}/reports`,{name,description,activeStructureId:structureId||null});setReports(x=>[...x,r]);setReportId(r.id);setNewReport(false);setNotice(`Report “${r.name}” created successfully`)};
 const createStructure=async(name:string)=>{const s=await postJson<ReportStructure>(`/projects/${projectId}/structures`,{name,description:''});setStructures(current=>[...current.filter(x=>x.id!==s.id),s]);setStructureId(s.id);setElements([]);setSelectedId('');setNewStructure(false);setNotice(`Structure “${s.name}” created successfully`)};
 const currentProject=projects.find(p=>p.id===projectId),currentReport=reports.find(r=>r.id===reportId),currentStructure=structures.find(s=>s.id===structureId);
 const exportObject=(name:string,data:any)=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=name.replace(/[^a-z0-9-_]+/gi,'-').toLowerCase()+'.json';a.click();URL.revokeObjectURL(a.href)};
 const duplicateProject=async()=>{if(!currentProject)return;const p=await postJson<Project>(`/projects/${projectId}/duplicate`,{name:`${currentProject.name} — Copy`});await loadProjects();setProjectId(p.id);setNotice('Project saved as a new copy')};
 const duplicateReport=async()=>{if(!currentReport)return;const r=await postJson<Report>(`/reports/${reportId}/duplicate`,{name:`${currentReport.name} — Copy`});await loadReports();setReportId(r.id);setNotice('Report saved as a new copy')};
 const duplicateStructure=async()=>{if(!currentStructure)return;const st=await postJson<ReportStructure>(`/structures/${structureId}/duplicate`,{name:`${currentStructure.name} — Copy`});await loadStructures();setStructureId(st.id);setNotice('Structure saved as a new copy')};
 const deleteProject=()=>{if(currentProject)setConfirmAction({kind:'project',title:'Delete project',message:'All reports, structures, and related project records will be permanently removed.',name:currentProject.name})};
 const deleteReport=()=>{if(currentReport)setConfirmAction({kind:'report',title:'Delete report',message:'This report record will be permanently removed. Its reusable structure will remain available.',name:currentReport.name})};
 const deleteStructure=()=>{if(currentStructure)setConfirmAction({kind:'structure',title:'Delete structure',message:'This reusable structure and its elements will be permanently removed.',name:currentStructure.name})};
 const confirmDelete=async()=>{if(!confirmAction||deleting)return;setDeleting(true);try{if(confirmAction.kind==='element'&&confirmAction.id){await deleteJson(`/elements/${confirmAction.id}`);setSelectedId('');await loadElements();setNotice('Element deleted')}else if(confirmAction.kind==='project'&&currentProject){await deleteJson(`/projects/${projectId}`);const remaining=projects.filter(p=>p.id!==projectId);setProjects(remaining);setProjectId(remaining[0]?.id||'');setNotice('Project deleted')}else if(confirmAction.kind==='report'&&currentReport){await deleteJson(`/reports/${reportId}`);await loadReports();setNotice('Report deleted')}else if(confirmAction.kind==='structure'&&currentStructure){await deleteJson(`/structures/${structureId}`);await loadStructures();setNotice('Structure deleted')}setConfirmAction(null)}catch(e:any){setNotice(e?.message||'Delete failed')}finally{setDeleting(false)}};
 const applyStructure=async()=>{if(!currentReport||!currentStructure)return;const r=await postJson<Report>(`/reports/${reportId}/apply-structure`,{structureId});setReports(x=>x.map(y=>y.id===r.id?r:y));setNotice(`Applied ${currentStructure.name} v${currentStructure.version} to ${currentReport.name}`)};
 return <><PageHeader title="Report Structure Studio" subtitle="Create reusable, five-level report structures for multiple projects" actions={<><Button variant="secondary" onClick={()=>setNewProject(true)}><FolderPlus size={15}/> Project</Button><Button variant="secondary" onClick={()=>setNewStructure(true)} disabled={!projectId}><Plus size={15}/> Structure</Button><Button onClick={()=>setImportOpen(true)} disabled={!structureId}><Upload size={15}/> Import</Button></>}/>
 <div className="entityCommandBar">
 <CommandMenu label="Project" disabled={false} items={[['New Project',()=>setNewProject(true),false],['Save Project',()=>setNotice('Project is saved automatically'),!projectId],['Save Project As',duplicateProject,!projectId],['Export Project',()=>currentProject&&exportObject(currentProject.name,{project:currentProject,reports,structures}),!projectId],['Delete Project',deleteProject,!projectId,true]]}/>
 <select aria-label="Current project" value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Select project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>
 <CommandMenu label="Report" disabled={!projectId} items={[['New Report',()=>setNewReport(true),!projectId],['Save Report',()=>setNotice('Report is saved automatically'),!reportId],['Save Report As',duplicateReport,!reportId],['Export Report',()=>currentReport&&exportObject(currentReport.name,currentReport),!reportId],['Apply Current Structure',applyStructure,!reportId||!structureId],['Delete Report',deleteReport,!reportId,true]]}/>
 <select aria-label="Current report" value={reportId} onChange={e=>setReportId(e.target.value)} disabled={!projectId}><option value="">Select report</option>{reports.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select>
 <CommandMenu label="Structure" disabled={!projectId} items={[['New Structure',()=>setNewStructure(true),!projectId],['Save Structure',()=>setNotice('Structure changes are versioned automatically'),!structureId],['Save Structure As',duplicateStructure,!structureId],['Import Structure',()=>setImportOpen(true),!structureId],['Export Structure',()=>currentStructure&&exportObject(currentStructure.name,{structure:currentStructure,elements}),!structureId],['Apply to Current Report',applyStructure,!reportId||!structureId],['Delete Structure',deleteStructure,!structureId,true]]}/>
 <select aria-label="Current structure" value={structureId} onChange={e=>setStructureId(e.target.value)} disabled={!projectId}><option value="">Select structure</option>{structures.map(st=><option key={st.id} value={st.id}>{st.name} · v{st.version}</option>)}</select>
 </div>
 {notice&&<div className="notice" onClick={()=>setNotice('')}>{notice}<span>×</span></div>}
 <div className="structureToolbar"><span>Add at {selected?'selection':'root'}:</span>{TYPES.map(t=><button key={t.value} onClick={()=>add(t.value)} title={`Add ${t.label} at selected tree position`}>{t.value==='image'?<ImageIcon size={14}/>:<Plus size={13}/>} {t.label}</button>)}</div>
 <div className={`structureWorkbench ${inspectorVisible?'':'inspectorHidden'}`}><Card className="structureTreeCard"><div className="cardTitle"><div><h3>Structure tree</h3><small>Use + to add at an exact point. Right-click an element for type and delete tools. Paragraphs can expand inline.</small></div><Button variant="secondary" onClick={()=>setInspectorVisible(v=>!v)}>{inspectorVisible?<PanelRightClose size={15}/>:<PanelRightOpen size={15}/>} {inspectorVisible?'Hide':'Show'} details</Button></div><div className={'rootDrop '+(dropHint?.kind==='root'?'dropActive':'')+(dropHint?.kind==='invalid'&&!dropHint.targetId?' dropInvalid':'')} onDragEnter={e=>{e.preventDefault();const dragged=elements.find(x=>x.id===draggedId);const valid=!!dragged&&canParent(dragged.type,null);setDropHint({kind:valid?'root':'invalid',parentId:null,index:(children.get(null)||[]).length,label:valid?'Move to the end of the document root':'This heading level cannot be placed at document root'})}} onDragOver={e=>{e.preventDefault();const dragged=elements.find(x=>x.id===draggedId);const valid=!!dragged&&canParent(dragged.type,null);e.dataTransfer.dropEffect=valid?'move':'none';setDropHint({kind:valid?'root':'invalid',parentId:null,index:(children.get(null)||[]).length,label:valid?'Move to the end of the document root':'This heading level cannot be placed at document root'})}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setDropHint(null)}} onDrop={e=>{if(dropHint?.kind==='root')onDrop(e,null,(children.get(null)||[]).length);else e.preventDefault()}}>{dropHint?.kind==='root'?<><b>Release to place at document root</b><span>{dropHint.label}</span></>:dropHint?.kind==='invalid'&&!dropHint.targetId?<><b>Placement not allowed</b><span>{dropHint.label}</span></>:'Drop here to move to the document root'}</div><Tree parentId={null} childrenMap={children} numbering={numbering} expanded={expanded} setExpanded={setExpanded} selectedId={selectedId} setSelectedId={setSelectedId} onDrop={onDrop} onAdd={add} onContext={(element:StructureElement,ev:React.MouseEvent)=>{ev.preventDefault();setSelectedId(element.id);setContextMenu({id:element.id,x:ev.clientX,y:ev.clientY})}} contentExpanded={contentExpanded} setContentExpanded={setContentExpanded} dropHint={dropHint} setDropHint={setDropHint} draggedId={draggedId} setDraggedId={setDraggedId}/>{!elements.length&&<div className="emptyState"><b>Start the structure</b><p>Add a title, chapter, heading, content element, or import an existing document.</p></div>}</Card>
 {inspectorVisible&&<Card className="elementInspector persistentInspector">{selected?<Inspector element={selected} parent={elements.find(e=>e.id===selected.parentId)} childCount={(children.get(selected.id)||[]).length} number={numbering.get(selected.id)} onSave={update} onDelete={()=>remove(selected)}/>:<div className="emptyState"><b>Select an element</b><p>Its complete editable properties remain available here while you work in the tree.</p></div>}</Card>}</div>
 {contextMenu&&<ElementContextMenu element={elements.find(e=>e.id===contextMenu.id)!} x={contextMenu.x} y={contextMenu.y} onClose={()=>setContextMenu(null)} onType={changeType} onDelete={(e:StructureElement)=>{setContextMenu(null);remove(e)}} onAdd={(type:StructureElementType,mode:'child'|'after'|'caption')=>{const e=elements.find(x=>x.id===contextMenu.id)!;const siblings=children.get(e.parentId||null)||[];setContextMenu(null);add(type,mode==='caption'?{parentId:e.parentId||null,index:siblings.findIndex(x=>x.id===e.id)+1,captionForId:e.id}:mode==='child'?{parentId:e.id,index:(children.get(e.id)||[]).length}:{parentId:e.parentId||null,index:siblings.findIndex(x=>x.id===e.id)+1})}}/>}
 <ConfirmDialog open={!!confirmAction} title={confirmAction?.title||'Confirm deletion'} message={<><span>{confirmAction?.message}</span><br/><strong>“{confirmAction?.name}”</strong></>} details="This action cannot be undone." confirmLabel={confirmAction?.kind==='project'?'Delete Project':confirmAction?.kind==='report'?'Delete Report':confirmAction?.kind==='structure'?'Delete Structure':'Delete Element'} busy={deleting} onCancel={()=>!deleting&&setConfirmAction(null)} onConfirm={confirmDelete}/>
 {newProject&&<NameModal title="Create project" label="Project name" onClose={()=>setNewProject(false)} onCreate={createProject}/>} {newReport&&<NameModal title="Create report" label="Report name" onClose={()=>setNewReport(false)} onCreate={createReport}/>} {newStructure&&<NameModal title="Create report structure" label="Structure name" onClose={()=>setNewStructure(false)} onCreate={createStructure}/>} {importOpen&&<ImportModal structureId={structureId} onClose={()=>setImportOpen(false)} onApplied={()=>{setImportOpen(false);loadElements()}}/>}</>}
function CommandMenu({label,items,disabled}:{label:string;disabled?:boolean;items:[string,()=>void,boolean?,boolean?][]}){return <details className="commandMenu"><summary className={disabled?'disabled':''}>{label}<ChevronDown size={14}/></summary><div className="commandMenuPopup">{items.map(([text,action,itemDisabled,danger])=><button key={text} disabled={itemDisabled} className={danger?'danger':''} onClick={e=>{e.preventDefault();if(!itemDisabled){action();(e.currentTarget.closest('details') as HTMLDetailsElement)?.removeAttribute('open')}}}>{text}</button>)}</div></details>}
function ElementContextMenu({element,x,y,onClose,onType,onDelete,onAdd}:{element:StructureElement;x:number;y:number;onClose:()=>void;onType:(element:StructureElement,type:StructureElementType)=>void;onDelete:(element:StructureElement)=>void;onAdd:(type:StructureElementType,mode:'child'|'after'|'caption')=>void}){
 useEffect(()=>{const close=()=>onClose();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose()};window.addEventListener('pointerdown',close);window.addEventListener('keydown',key);return()=>{window.removeEventListener('pointerdown',close);window.removeEventListener('keydown',key)}},[onClose]);
 const left=Math.min(x,window.innerWidth-270),top=Math.min(y,window.innerHeight-390);
 const matchingCaption=element.type==='table'?'tableCaption':element.type==='image'?'imageCaption':element.type==='textBox'?'textBoxCaption':null;
 return createPortal(<div className="elementContextMenu" style={{left:Math.max(8,left),top:Math.max(8,top)}} onPointerDown={e=>e.stopPropagation()} role="menu" aria-label="Element actions">
  <div className="contextTitle">{element.title||TYPES.find(t=>t.value===element.type)?.label||'Element'}</div>
  {heading(element.type)&&<button onClick={()=>onAdd('paragraph','child')}><Plus size={14}/> Add content child</button>}
  <button onClick={()=>onAdd('paragraph','after')}><Plus size={14}/> Add paragraph after</button>
  {matchingCaption&&<button onClick={()=>onAdd(matchingCaption,'caption')}><Plus size={14}/> Add {TYPES.find(t=>t.value===matchingCaption)?.label}</button>}
  <div className="contextDivider"/>
  <label>Change element type<select value={element.type} onChange={e=>onType(element,e.target.value as StructureElementType)}>{TYPES.map(t=><option key={t.value} value={t.value}>{t.label}</option>)}</select></label>
  <div className="contextDivider"/>
  <button className="danger" onClick={()=>onDelete(element)}><Trash2 size={14}/> Delete element</button>
 </div>,document.body)
}
function Tree({parentId,childrenMap,numbering,expanded,setExpanded,selectedId,setSelectedId,onDrop,onAdd,onContext,contentExpanded,setContentExpanded,dropHint,setDropHint,draggedId,setDraggedId}:{parentId:string|null;childrenMap:Map<string|null,StructureElement[]>;numbering:Map<string,string>;expanded:Set<string>;setExpanded:any;selectedId:string;setSelectedId:any;onDrop:any;onAdd:any;onContext:any;contentExpanded:Set<string>;setContentExpanded:any;dropHint:DropHint|null;setDropHint:any;draggedId:string;setDraggedId:any}){
 const list=childrenMap.get(parentId)||[];
 const allElements=Array.from(childrenMap.values()).flat();
 const dragged=allElements.find(x=>x.id===draggedId);
 return <div className="treeBranch">{list.map((e,i)=>{
  const kids=childrenMap.get(e.id)||[];
  const open=expanded.has(e.id);
  const isContent=e.type==='paragraph'||e.type==='textBox'||e.type==='bullets'||e.type==='numberedList'||captionType(e.type);
  const showContent=contentExpanded.has(e.id);
  const hint=dropHint?.targetId===e.id?dropHint:null;
  const setNodeHint=(ev:React.DragEvent)=>{
   ev.preventDefault();ev.stopPropagation();
   if(!dragged){ev.dataTransfer.dropEffect='none';return}
   const rect=ev.currentTarget.getBoundingClientRect();
   const ratio=(ev.clientY-rect.top)/Math.max(rect.height,1);
   const wantsInside=heading(e.type)&&ratio>=.28&&ratio<=.72;
   let kind:'before'|'inside'|'after'=wantsInside?'inside':ratio<.5?'before':'after';
   const targetParent=kind==='inside'?e.id:parentId;
   const targetParentType=kind==='inside'?e.type:(parentId?allElements.find(x=>x.id===parentId)?.type||null:null);
   const valid=canParent(dragged.type,targetParentType);
   const index=kind==='inside'?kids.length:i+(kind==='after'?1:0);
   if(!valid){
    ev.dataTransfer.dropEffect='none';
    const d=depth(dragged.type);
    const requirement=d&&d>1?`Heading ${d} must be a direct child of Heading ${d-1}.`:d===1?'Heading 1 may be placed at root or under a Title/Chapter.':'Content elements may be placed at root or inside any Title, Chapter or Heading.';
    setDropHint({kind:'invalid',targetId:e.id,parentId:targetParent,index,label:requirement});
    return;
   }
   ev.dataTransfer.dropEffect='move';
   const label=kind==='inside'?`Place inside “${e.title||TYPES.find(x=>x.value===e.type)?.label}” as its last child`:kind==='before'?`Place before “${e.title||preview(e)}”`:`Place after “${e.title||preview(e)}”`;
   setDropHint({kind,targetId:e.id,parentId:targetParent,index,label});
  };
  return <div key={e.id} className={'treeElement '+(hint?'dropTarget ':'')+(hint?.kind==='invalid'?'invalidTarget':'')}>
   {hint?.kind==='before'&&<div className="dropInsertionLine before"><span>Release to place here</span></div>}
   <div className={'structureNode '+(selectedId===e.id?'active ':'')+(captionType(e.type)?'captionNode ':'')+(hint?.kind==='inside'?'dropInside ':'')+(hint?.kind==='invalid'?'dropInvalid ':'')} draggable={!captionType(e.type)} onContextMenu={ev=>onContext(e,ev)} onDragStart={ev=>{if(captionType(e.type)){ev.preventDefault();return}ev.dataTransfer.setData('text/aris-element',e.id);ev.dataTransfer.effectAllowed='move';setDraggedId(e.id)}} onDragEnd={()=>{setDraggedId('');setDropHint(null)}} onDragEnter={setNodeHint} onDragOver={setNodeHint} onDragLeave={ev=>{if(!ev.currentTarget.contains(ev.relatedTarget as Node))setDropHint(null)}} onDrop={ev=>{if(hint&&hint.kind!=='invalid')onDrop(ev,hint.parentId,hint.index);else ev.preventDefault()}} onClick={()=>setSelectedId(e.id)}>
    <GripVertical size={14} className="dragGrip"/>
    <button className="treeToggle" onClick={ev=>{ev.stopPropagation();setExpanded((x:Set<string>)=>{const n=new Set(x);n.has(e.id)?n.delete(e.id):n.add(e.id);return n})}}>{kids.length?(open?<ChevronDown size={14}/>:<ChevronRight size={14}/>):<span/>}</button>
    {numbering.get(e.id)&&<span className="dynamicNumber">{numbering.get(e.id)}</span>}
    <Badge>{TYPES.find(x=>x.value===e.type)?.label||e.type}</Badge>
    <div className="nodeBody"><span className="nodeText">{e.title||(!isContent?preview(e):'Untitled content')}</span>{isContent&&e.content&&<div className={'inlineContent '+(showContent?'expanded':'collapsed')} onClick={ev=>{ev.stopPropagation();setContentExpanded((current:Set<string>)=>{const next=new Set(current);next.has(e.id)?next.delete(e.id):next.add(e.id);return next})}}>{e.content}</div>}{hint?.kind==='inside'&&<div className="dropInsideHint">Release to add as last child</div>}{hint?.kind==='invalid'&&<div className="dropInvalidHint">{hint.label}</div>}</div>
    {heading(e.type)&&<button className="nodeAdd" title="Add a content child at this point" onClick={ev=>{ev.stopPropagation();onAdd('paragraph',{parentId:e.id,index:kids.length})}}><Plus size={14}/></button>}
    <button className="nodeMenu" title="Element actions" onClick={ev=>{ev.stopPropagation();onContext(e,ev)}}><MoreVertical size={15}/></button>
   </div>
   {hint?.kind==='after'&&<div className="dropInsertionLine after"><span>Release to place here</span></div>}
   {open&&heading(e.type)&&<div className="treeChildren"><Tree parentId={e.id} childrenMap={childrenMap} numbering={numbering} expanded={expanded} setExpanded={setExpanded} selectedId={selectedId} setSelectedId={setSelectedId} onDrop={onDrop} onAdd={onAdd} onContext={onContext} contentExpanded={contentExpanded} setContentExpanded={setContentExpanded} dropHint={dropHint} setDropHint={setDropHint} draggedId={draggedId} setDraggedId={setDraggedId}/>{!kids.length&&<button className="emptyChildAdd" onClick={()=>onAdd('paragraph',{parentId:e.id,index:0})}><Plus size={13}/> Add first content child</button>}</div>}
   <button className="betweenAdd" title="Add paragraph after this element" onClick={()=>onAdd('paragraph',{parentId,index:i+1})}><Plus size={12}/></button>
  </div>
 })}</div>
}
function Inspector({element,parent,childCount,number,onSave,onDelete}:{element:StructureElement;parent?:StructureElement;childCount:number;number?:string;onSave:any;onDelete:any}){const[draft,setDraft]=useState(element);useEffect(()=>setDraft(element),[element.id,element]);const props=draft.properties||{};const setProp=(k:string,v:any)=>setDraft({...draft,properties:{...props,[k]:v}});return <><div className="cardTitle"><div><Badge>{TYPES.find(x=>x.value===draft.type)?.label}</Badge><h3>{number?`${number} `:''}{draft.title||'Untitled element'}</h3></div><Button variant="danger" onClick={onDelete}><Trash2 size={14}/> Delete</Button></div><div className="readonlyGrid"><div><label>Parent element</label><b>{parent?parent.title||preview(parent):'Root'}</b></div><div><label>Child elements</label><b>{childCount}</b></div><div><label>Calculated number</label><b>{number||'Not numbered'}</b></div><div><label>Element ID</label><b>{draft.id}</b></div></div><div className="formGrid"><label>Element type<select value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value as StructureElementType})}>{TYPES.map(t=><option value={t.value} key={t.value}>{t.label}</option>)}</select></label><label className="full">Title / caption<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label>{draft.type==='table'?<TableEditor value={draft.content} onChange={content=>setDraft({...draft,content})}/>:draft.type==='image'?<label className="full">Image data or source reference<textarea value={draft.content} onChange={e=>setDraft({...draft,content:e.target.value})}/></label>:<label className="full">Content<textarea rows={draft.type==='textBox'?6:4} value={draft.content} onChange={e=>setDraft({...draft,content:e.target.value})}/></label>}{heading(draft.type)&&<><label className="full">Scope definition<textarea value={props.description||''} onChange={e=>setProp('description',e.target.value)}/></label><label>Owner<input value={props.owner||''} onChange={e=>setProp('owner',e.target.value)}/></label><label>Reviewer<input value={props.reviewer||''} onChange={e=>setProp('reviewer',e.target.value)}/></label><label>Word limit<input type="number" value={props.wordLimit||600} onChange={e=>setProp('wordLimit',Number(e.target.value))}/></label><Lines label="Inclusion rules" value={props.include} onChange={(v:string[])=>setProp('include',v)}/><Lines label="Exclusion rules" value={props.exclude} onChange={(v:string[])=>setProp('exclude',v)}/><Lines label="Evidence types" value={props.evidenceTypes} onChange={(v:string[])=>setProp('evidenceTypes',v)}/><Lines label="Expected metrics" value={props.expectedMetrics} onChange={(v:string[])=>setProp('expectedMetrics',v)}/></>}</div><div className="modalActions"><Button onClick={()=>onSave(draft)}><Save size={15}/> Save changes</Button></div></>}
function ImportModal({structureId,onClose,onApplied}:{structureId:string;onClose:any;onApplied:any}){const[tab,setTab]=useState<'paste'|'file'>('paste'),[text,setText]=useState(''),[blocks,setBlocks]=useState<any[]>([]),[mode,setMode]=useState('append'),[busy,setBusy]=useState(false),[error,setError]=useState('');const analyseText=async()=>{setBusy(true);try{const r=await postJson<any>(`/structures/${structureId}/import-text`,{text});setBlocks(r.blocks)}catch(e:any){setError(e.message)}finally{setBusy(false)}};const file=async(f:File)=>{setBusy(true);setError('');try{const fd=new FormData();fd.append('file',f);const r=await fetch(`${(import.meta as any).env.VITE_API_URL||'http://localhost:4000/api'}/structures/${structureId}/import-file`,{method:'POST',body:fd});const b=await r.json();if(!r.ok)throw new Error(b.error);setBlocks(b.blocks)}catch(e:any){setError(e.message)}finally{setBusy(false)}};const apply=async()=>{setBusy(true);try{await postJson(`/structures/${structureId}/apply-import`,{blocks,mode});onApplied()}catch(e:any){setError(e.message)}finally{setBusy(false)}};return <Modal title="Import report structure" onClose={onClose} width="900px"><div className="importTabs"><button className={tab==='paste'?'active':''} onClick={()=>setTab('paste')}>Paste text</button><button className={tab==='file'?'active':''} onClick={()=>setTab('file')}>Upload or drag file</button></div>{tab==='paste'?<><textarea className="pasteArea" placeholder={'Paste headings and content here.\n1 Institutional Overview\n1.1 Vision and Mission\n- Evidence item'} value={text} onChange={e=>setText(e.target.value)}/><Button onClick={analyseText} disabled={!text.trim()||busy}>Analyse pasted content</Button></>:<label className="fileDrop" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const f=e.dataTransfer.files[0];if(f)file(f)}}><FileUp size={34}/><b>Drop a document here</b><span>DOCX, PDF, XLSX, PPTX, TXT, Markdown, HTML, CSV and RTF</span><input type="file" accept=".docx,.pdf,.xlsx,.pptx,.txt,.md,.html,.htm,.csv,.rtf" onChange={e=>e.target.files?.[0]&&file(e.target.files[0])}/></label>}{error&&<div className="finding error">{error}</div>}{blocks.length>0&&<><div className="importPreview"><h4>Detected elements ({blocks.length})</h4>{blocks.slice(0,100).map((b,i)=><div key={i}><Badge>{b.type}{b.level?` ${b.level}`:''}</Badge><span>{b.text||(b.items||[]).join(', ')||b.caption||'Embedded element'}</span></div>)}</div><label>Import mode<select value={mode} onChange={e=>setMode(e.target.value)}><option value="append">Append to current structure</option><option value="replace">Replace current structure</option></select></label></>}<div className="modalActions"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button onClick={apply} disabled={!blocks.length||busy}>Import {blocks.length} elements</Button></div></Modal>}
function NameModal({title,label,onClose,onCreate}:{title:string;label:string;onClose:any;onCreate:(name:string,description?:string)=>Promise<void>}){const[name,setName]=useState(''),[description,setDescription]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const submit=async(e?:React.FormEvent)=>{e?.preventDefault();const value=name.trim();if(!value||busy)return;setBusy(true);setError('');try{await onCreate(value,description.trim())}catch(err:any){setError(err?.message||'Unable to create project. Please confirm that the API service is running.');setBusy(false)}};return <Modal title={title} onClose={()=>!busy&&onClose()}><form onSubmit={submit} className="nameModalForm"><label>{label}<input autoFocus value={name} maxLength={160} onChange={e=>setName(e.target.value)} placeholder="Enter a clear project name" disabled={busy}/></label>{title.toLowerCase().includes('project')&&<label>Description <span className="optionalText">(optional)</span><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Purpose or scope of this project" disabled={busy}/></label>}{error&&<div className="formError" role="alert">{error}</div>}<div className="modalActions"><Button variant="secondary" onClick={onClose} disabled={busy}>Cancel</Button><Button type="submit" disabled={!name.trim()||busy}>{busy?'Creating…':'Create'}</Button></div></form></Modal>}
function Lines({label,value=[],onChange}:{label:string;value?:string[];onChange:any}){return <label>{label}<textarea value={value.join('\n')} onChange={e=>onChange(e.target.value.split('\n').map(x=>x.trim()).filter(Boolean))}/></label>}
function TableEditor({value,onChange}:{value:string;onChange:any}){let d={columns:['Column 1','Column 2'],rows:[['','']]};try{d=JSON.parse(value||'{}');if(!d.columns)d.columns=['Column 1','Column 2'];if(!d.rows)d.rows=[['','']]}catch{}return <label className="full">Table data<textarea rows={8} value={[d.columns.join(' | '),...d.rows.map((r:string[])=>r.join(' | '))].join('\n')} onChange={e=>{const lines=e.target.value.split('\n');onChange(JSON.stringify({columns:(lines.shift()||'').split('|').map(x=>x.trim()),rows:lines.map(x=>x.split('|').map(y=>y.trim()))}))}}/><small>Use one row per line and separate cells with |.</small></label>}
function preview(e:StructureElement){return (e.content||e.type).slice(0,80)}
