import {useEffect,useMemo,useState} from 'react';
import {ChevronDown,ChevronRight,Copy,FileUp,FolderPlus,GripVertical,Image as ImageIcon,Plus,Save,Trash2,Upload,Users} from 'lucide-react';
import PageHeader from '../components/PageHeader';import{Badge,Button,Card,ConfirmDialog,Modal}from'../components/UI';import{deleteJson,getJson,patchJson,postJson}from'../api';import type{Project,Report,ReportStructure,StructureElement,StructureElementType}from'../types';
const TYPES:{value:StructureElementType;label:string}[]=[['title','Title'],['chapter','Chapter'],['heading1','Heading 1'],['heading2','Heading 2'],['heading3','Heading 3'],['heading4','Heading 4'],['heading5','Heading 5'],['paragraph','Paragraph'],['bullets','Bullet list'],['numberedList','Numbered list'],['table','Table'],['textBox','Text box'],['image','Image']].map(([value,label])=>({value:value as StructureElementType,label}));
const heading=(t:string)=>t==='chapter'||/^heading[1-5]$/.test(t);const depth=(t:string)=>t==='chapter'?0:t.startsWith('heading')?Number(t.slice(7)):null;
export default function Structure(){
 const[projects,setProjects]=useState<Project[]>([]),[projectId,setProjectId]=useState(''),[reports,setReports]=useState<Report[]>([]),[reportId,setReportId]=useState(''),[structures,setStructures]=useState<ReportStructure[]>([]),[structureId,setStructureId]=useState(''),[elements,setElements]=useState<StructureElement[]>([]),[selectedId,setSelectedId]=useState(''),[expanded,setExpanded]=useState<Set<string>>(new Set()),[notice,setNotice]=useState(''),[newProject,setNewProject]=useState(false),[newReport,setNewReport]=useState(false),[newStructure,setNewStructure]=useState(false),[importOpen,setImportOpen]=useState(false),[confirmAction,setConfirmAction]=useState<null|{kind:'element'|'project'|'report'|'structure';title:string;message:string;name:string}>(null),[deleting,setDeleting]=useState(false);
 const loadProjects=async()=>{const p=await getJson<Project[]>('/projects');setProjects(p);if(!projectId&&p[0])setProjectId(p[0].id)};
 const loadReports=async(pid=projectId)=>{if(!pid){setReports([]);setReportId('');return}const r=await getJson<Report[]>(`/projects/${pid}/reports`);setReports(r);if(!r.some(x=>x.id===reportId))setReportId(r[0]?.id||'')};
 const loadStructures=async(pid=projectId)=>{if(!pid)return;const s=await getJson<ReportStructure[]>(`/projects/${pid}/structures`);setStructures(s);if(!s.some(x=>x.id===structureId))setStructureId(s[0]?.id||'')};
 const loadElements=async(sid=structureId)=>{if(!sid){setElements([]);return}const e=await getJson<StructureElement[]>(`/structures/${sid}/elements`);setElements(e);setExpanded(new Set(e.filter(x=>e.some(y=>y.parentId===x.id)).map(x=>x.id)));if(selectedId&&!e.some(x=>x.id===selectedId))setSelectedId('')};
 useEffect(()=>{loadProjects()},[]);useEffect(()=>{loadReports(projectId);loadStructures(projectId)},[projectId]);useEffect(()=>{loadElements(structureId)},[structureId]);useEffect(()=>{const r=reports.find(x=>x.id===reportId);if(r?.activeStructureId&&structures.some(s=>s.id===r.activeStructureId))setStructureId(r.activeStructureId)},[reportId]);
 const selected=elements.find(e=>e.id===selectedId)||null;const children=useMemo(()=>{const m=new Map<string|null,StructureElement[]>();elements.forEach(e=>{const k=e.parentId||null;m.set(k,[...(m.get(k)||[]),e])});m.forEach(a=>a.sort((x,y)=>x.order-y.order));return m},[elements]);
 const numbering=useMemo(()=>{const out=new Map<string,string>();const walk=(pid:string|null,prefix:number[]=[])=>{let n=0;for(const e of children.get(pid)||[]){if(heading(e.type)){n++;const nums=[...prefix,n];out.set(e.id,nums.join('.'));walk(e.id,nums)}else walk(e.id,prefix)}};walk(null);return out},[children]);
 const add=async(type:StructureElementType,parentId:string|null=selected?.id||null)=>{let finalParent=parentId;if(heading(type)){const d=depth(type)!;if(d===0)finalParent=null;else if(d===1&&!finalParent)finalParent=null;else if(!finalParent||depth(elements.find(e=>e.id===finalParent)?.type||'')!==d-1){setNotice(`Heading ${d} must be created under ${d===1?'a chapter or at root':'Heading '+(d-1)}.`);return}}const title=heading(type)||type==='title'?`New ${TYPES.find(x=>x.value===type)?.label}`:'';const e=await postJson<StructureElement>(`/structures/${structureId}/elements`,{type,parentId:finalParent,title,content:'',properties:heading(type)?{owner:'',reviewer:'',wordLimit:600,description:'',include:[],exclude:[],evidenceTypes:[],expectedMetrics:[],contributors:[]}:{}});await loadElements();setSelectedId(e.id);setExpanded(x=>new Set(x).add(finalParent||''))};
 const update=async(patch:Partial<StructureElement>)=>{if(!selected)return;const e=await patchJson<StructureElement>(`/elements/${selected.id}`,patch);setElements(a=>a.map(x=>x.id===e.id?e:x));setNotice('Saved')};
 const remove=()=>{if(!selected)return;setConfirmAction({kind:'element',title:'Delete structure element',message:'This element and every child element beneath it will be permanently removed.',name:selected.title||preview(selected)})};
 const onDrop=async(ev:React.DragEvent,targetParent:string|null,index:number)=>{ev.preventDefault();const id=ev.dataTransfer.getData('text/aris-element');if(!id)return;try{await postJson(`/elements/${id}/move`,{parentId:targetParent,index});await loadElements();setSelectedId(id)}catch(e:any){setNotice(e.message)}};
 const createProject=async(name:string,description='')=>{const p=await postJson<Project>('/projects',{name,description});setProjects(current=>[...current.filter(x=>x.id!==p.id),p]);setProjectId(p.id);setReports([]);setReportId('');setStructures([]);setStructureId('');setElements([]);setSelectedId('');setNewProject(false);setNotice(`Project “${p.name}” created successfully`)};
 const createReport=async(name:string,description='')=>{const r=await postJson<Report>(`/projects/${projectId}/reports`,{name,description,activeStructureId:structureId||null});setReports(x=>[...x,r]);setReportId(r.id);setNewReport(false);setNotice(`Report “${r.name}” created successfully`)};
 const createStructure=async(name:string)=>{const s=await postJson<ReportStructure>(`/projects/${projectId}/structures`,{name,description:''});setStructures(current=>[...current.filter(x=>x.id!==s.id),s]);setStructureId(s.id);setElements([]);setSelectedId('');setNewStructure(false);setNotice(`Structure “${s.name}” created successfully`)};
 const currentProject=projects.find(p=>p.id===projectId),currentReport=reports.find(r=>r.id===reportId),currentStructure=structures.find(s=>s.id===structureId);
 const exportObject=(name:string,data:any)=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=name.replace(/[^a-z0-9-_]+/gi,'-').toLowerCase()+'.json';a.click();URL.revokeObjectURL(a.href)};
 const duplicateProject=async()=>{if(!currentProject)return;const p=await postJson<Project>(`/projects/${projectId}/duplicate`,{name:`${currentProject.name} — Copy`});await loadProjects();setProjectId(p.id);setNotice('Project saved as a new copy')};
 const duplicateReport=async()=>{if(!currentReport)return;const r=await postJson<Report>(`/reports/${reportId}/duplicate`,{name:`${currentReport.name} — Copy`});await loadReports();setReportId(r.id);setNotice('Report saved as a new copy')};
 const duplicateStructure=async()=>{if(!currentStructure)return;const st=await postJson<ReportStructure>(`/structures/${structureId}/duplicate`,{name:`${currentStructure.name} — Copy`});await loadStructures();setStructureId(st.id);setNotice('Structure saved as a new copy')};
 const deleteProject=()=>{if(currentProject)setConfirmAction({kind:'project',title:'Delete project',message:'All reports, structures, and related project records will be permanently removed.',name:currentProject.name})};
 const deleteReport=()=>{if(currentReport)setConfirmAction({kind:'report',title:'Delete report',message:'This report record will be permanently removed. Its reusable structure will remain available.',name:currentReport.name})};
 const deleteStructure=()=>{if(currentStructure)setConfirmAction({kind:'structure',title:'Delete structure',message:'This reusable structure and its elements will be permanently removed.',name:currentStructure.name})};
 const confirmDelete=async()=>{if(!confirmAction||deleting)return;setDeleting(true);try{if(confirmAction.kind==='element'&&selected){await deleteJson(`/elements/${selected.id}`);setSelectedId('');await loadElements();setNotice('Element deleted')}else if(confirmAction.kind==='project'&&currentProject){await deleteJson(`/projects/${projectId}`);const remaining=projects.filter(p=>p.id!==projectId);setProjects(remaining);setProjectId(remaining[0]?.id||'');setNotice('Project deleted')}else if(confirmAction.kind==='report'&&currentReport){await deleteJson(`/reports/${reportId}`);await loadReports();setNotice('Report deleted')}else if(confirmAction.kind==='structure'&&currentStructure){await deleteJson(`/structures/${structureId}`);await loadStructures();setNotice('Structure deleted')}setConfirmAction(null)}catch(e:any){setNotice(e?.message||'Delete failed')}finally{setDeleting(false)}};
 const applyStructure=async()=>{if(!currentReport||!currentStructure)return;const r=await postJson<Report>(`/reports/${reportId}/apply-structure`,{structureId});setReports(x=>x.map(y=>y.id===r.id?r:y));setNotice(`Applied ${currentStructure.name} v${currentStructure.version} to ${currentReport.name}`)};
 return <><PageHeader title="Report Structure Studio" subtitle="Create reusable, five-level report structures for multiple projects" actions={<><Button variant="secondary" onClick={()=>setNewProject(true)}><FolderPlus size={15}/> Project</Button><Button variant="secondary" onClick={()=>setNewStructure(true)} disabled={!projectId}><Plus size={15}/> Structure</Button><Button onClick={()=>setImportOpen(true)} disabled={!structureId}><Upload size={15}/> Import</Button></>}/>
 <div className="entityCommandBar">
 <CommandMenu label="Project" disabled={false} items={[['New Project',()=>setNewProject(true),false],['Save Project',()=>setNotice('Project is saved automatically'),!projectId],['Save Project As',duplicateProject,!projectId],['Export Project',()=>currentProject&&exportObject(currentProject.name,{project:currentProject,reports,structures}),!projectId],['Delete Project',deleteProject,!projectId,true]]}/>
 <select aria-label="Current project" value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Select project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>
 <CommandMenu label="Report" disabled={!projectId} items={[['New Report',()=>setNewReport(true),!projectId],['Save Report',()=>setNotice('Report is saved automatically'),!reportId],['Save Report As',duplicateReport,!reportId],['Export Report',()=>currentReport&&exportObject(currentReport.name,currentReport),!reportId],['Apply Current Structure',applyStructure,!reportId||!structureId],['Delete Report',deleteReport,!reportId,true]]}/>
 <select aria-label="Current report" value={reportId} onChange={e=>setReportId(e.target.value)} disabled={!projectId}><option value="">Select report</option>{reports.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select>
 <CommandMenu label="Structure" disabled={!projectId} items={[['New Structure',()=>setNewStructure(true),!projectId],['Save Structure',()=>setNotice('Structure changes are versioned automatically'),!structureId],['Save Structure As',duplicateStructure,!structureId],['Import Structure',()=>setImportOpen(true),!structureId],['Export Structure',()=>currentStructure&&exportObject(currentStructure.name,{structure:currentStructure,elements}),!structureId],['Apply to Current Report',applyStructure,!reportId||!structureId],['Delete Structure',deleteStructure,!structureId,true]]}/>
 <select aria-label="Current structure" value={structureId} onChange={e=>setStructureId(e.target.value)} disabled={!projectId}><option value="">Select structure</option>{structures.map(st=><option key={st.id} value={st.id}>{st.name} · v{st.version}</option>)}</select>
 </div>
 {notice&&<div className="notice" onClick={()=>setNotice('')}>{notice}<span>×</span></div>}
 <div className="structureToolbar"><span>Add element:</span>{TYPES.map(t=><button key={t.value} onClick={()=>add(t.value)} title={`Add ${t.label}`}>{t.value==='image'?<ImageIcon size={14}/>:<Plus size={13}/>} {t.label}</button>)}</div>
 <div className="structureWorkbench"><Card className="structureTreeCard"><div className="cardTitle"><div><h3>Structure tree</h3><small>Numbers are calculated from current tree position. Drag any element to reorder or re-parent it.</small></div></div><div className="rootDrop" onDragOver={e=>e.preventDefault()} onDrop={e=>onDrop(e,null,(children.get(null)||[]).length)}>Drop here to move to root</div><Tree parentId={null} childrenMap={children} numbering={numbering} expanded={expanded} setExpanded={setExpanded} selectedId={selectedId} setSelectedId={setSelectedId} onDrop={onDrop}/>{!elements.length&&<div className="emptyState"><b>Start the structure</b><p>Add a title, chapter, heading, content element, or import an existing document.</p></div>}</Card>
 <Card className="elementInspector">{selected?<Inspector element={selected} parent={elements.find(e=>e.id===selected.parentId)} childCount={(children.get(selected.id)||[]).length} number={numbering.get(selected.id)} onSave={update} onDelete={remove}/>:<div className="emptyState"><b>Select an element</b><p>Its editable properties, current parent and child information will appear here.</p></div>}</Card></div>
 <ConfirmDialog open={!!confirmAction} title={confirmAction?.title||'Confirm deletion'} message={<><span>{confirmAction?.message}</span><br/><strong>“{confirmAction?.name}”</strong></>} details="This action cannot be undone." confirmLabel={confirmAction?.kind==='project'?'Delete Project':confirmAction?.kind==='report'?'Delete Report':confirmAction?.kind==='structure'?'Delete Structure':'Delete Element'} busy={deleting} onCancel={()=>!deleting&&setConfirmAction(null)} onConfirm={confirmDelete}/>
 {newProject&&<NameModal title="Create project" label="Project name" onClose={()=>setNewProject(false)} onCreate={createProject}/>} {newReport&&<NameModal title="Create report" label="Report name" onClose={()=>setNewReport(false)} onCreate={createReport}/>} {newStructure&&<NameModal title="Create report structure" label="Structure name" onClose={()=>setNewStructure(false)} onCreate={createStructure}/>} {importOpen&&<ImportModal structureId={structureId} onClose={()=>setImportOpen(false)} onApplied={()=>{setImportOpen(false);loadElements()}}/>}</>}
function CommandMenu({label,items,disabled}:{label:string;disabled?:boolean;items:[string,()=>void,boolean?,boolean?][]}){return <details className="commandMenu"><summary className={disabled?'disabled':''}>{label}<ChevronDown size={14}/></summary><div className="commandMenuPopup">{items.map(([text,action,itemDisabled,danger])=><button key={text} disabled={itemDisabled} className={danger?'danger':''} onClick={e=>{e.preventDefault();if(!itemDisabled){action();(e.currentTarget.closest('details') as HTMLDetailsElement)?.removeAttribute('open')}}}>{text}</button>)}</div></details>}
function Tree({parentId,childrenMap,numbering,expanded,setExpanded,selectedId,setSelectedId,onDrop}:{parentId:string|null;childrenMap:Map<string|null,StructureElement[]>;numbering:Map<string,string>;expanded:Set<string>;setExpanded:any;selectedId:string;setSelectedId:any;onDrop:any}){const list=childrenMap.get(parentId)||[];return <div className="treeBranch">{list.map((e,i)=>{const kids=childrenMap.get(e.id)||[];const open=expanded.has(e.id);return <div key={e.id}><div className={'structureNode '+(selectedId===e.id?'active':'')} draggable onDragStart={ev=>{ev.dataTransfer.setData('text/aris-element',e.id);ev.dataTransfer.effectAllowed='move'}} onDragOver={ev=>ev.preventDefault()} onDrop={ev=>{ev.stopPropagation();onDrop(ev,parentId,i)}} onClick={()=>setSelectedId(e.id)}><GripVertical size={14}/><button className="treeToggle" onClick={ev=>{ev.stopPropagation();setExpanded((x:Set<string>)=>{const n=new Set(x);n.has(e.id)?n.delete(e.id):n.add(e.id);return n})}}>{kids.length?(open?<ChevronDown size={14}/>:<ChevronRight size={14}/>):<span/>}</button>{numbering.get(e.id)&&<span className="dynamicNumber">{numbering.get(e.id)}</span>}<Badge>{TYPES.find(x=>x.value===e.type)?.label||e.type}</Badge><span className="nodeText">{e.title||preview(e)}</span></div>{open&&<div className="treeChildren" onDragOver={ev=>ev.preventDefault()} onDrop={ev=>{ev.stopPropagation();onDrop(ev,e.id,kids.length)}}><Tree parentId={e.id} childrenMap={childrenMap} numbering={numbering} expanded={expanded} setExpanded={setExpanded} selectedId={selectedId} setSelectedId={setSelectedId} onDrop={onDrop}/>{!kids.length&&<small>Drop child elements here</small>}</div>}</div>})}</div>}
function Inspector({element,parent,childCount,number,onSave,onDelete}:{element:StructureElement;parent?:StructureElement;childCount:number;number?:string;onSave:any;onDelete:any}){const[draft,setDraft]=useState(element);useEffect(()=>setDraft(element),[element.id,element]);const props=draft.properties||{};const setProp=(k:string,v:any)=>setDraft({...draft,properties:{...props,[k]:v}});return <><div className="cardTitle"><div><Badge>{TYPES.find(x=>x.value===draft.type)?.label}</Badge><h3>{number?`${number} `:''}{draft.title||'Untitled element'}</h3></div><Button variant="danger" onClick={onDelete}><Trash2 size={14}/> Delete</Button></div><div className="readonlyGrid"><div><label>Parent element</label><b>{parent?parent.title||preview(parent):'Root'}</b></div><div><label>Child elements</label><b>{childCount}</b></div><div><label>Calculated number</label><b>{number||'Not numbered'}</b></div><div><label>Element ID</label><b>{draft.id}</b></div></div><div className="formGrid"><label>Element type<select value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value as StructureElementType})}>{TYPES.map(t=><option value={t.value} key={t.value}>{t.label}</option>)}</select></label><label className="full">Title / caption<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label>{draft.type==='table'?<TableEditor value={draft.content} onChange={content=>setDraft({...draft,content})}/>:draft.type==='image'?<label className="full">Image data or source reference<textarea value={draft.content} onChange={e=>setDraft({...draft,content:e.target.value})}/></label>:<label className="full">Content<textarea rows={draft.type==='textBox'?6:4} value={draft.content} onChange={e=>setDraft({...draft,content:e.target.value})}/></label>}{heading(draft.type)&&<><label className="full">Scope definition<textarea value={props.description||''} onChange={e=>setProp('description',e.target.value)}/></label><label>Owner<input value={props.owner||''} onChange={e=>setProp('owner',e.target.value)}/></label><label>Reviewer<input value={props.reviewer||''} onChange={e=>setProp('reviewer',e.target.value)}/></label><label>Word limit<input type="number" value={props.wordLimit||600} onChange={e=>setProp('wordLimit',Number(e.target.value))}/></label><Lines label="Inclusion rules" value={props.include} onChange={(v:string[])=>setProp('include',v)}/><Lines label="Exclusion rules" value={props.exclude} onChange={(v:string[])=>setProp('exclude',v)}/><Lines label="Evidence types" value={props.evidenceTypes} onChange={(v:string[])=>setProp('evidenceTypes',v)}/><Lines label="Expected metrics" value={props.expectedMetrics} onChange={(v:string[])=>setProp('expectedMetrics',v)}/></>}</div><div className="modalActions"><Button onClick={()=>onSave(draft)}><Save size={15}/> Save changes</Button></div></>}
function ImportModal({structureId,onClose,onApplied}:{structureId:string;onClose:any;onApplied:any}){const[tab,setTab]=useState<'paste'|'file'>('paste'),[text,setText]=useState(''),[blocks,setBlocks]=useState<any[]>([]),[mode,setMode]=useState('append'),[busy,setBusy]=useState(false),[error,setError]=useState('');const analyseText=async()=>{setBusy(true);try{const r=await postJson<any>(`/structures/${structureId}/import-text`,{text});setBlocks(r.blocks)}catch(e:any){setError(e.message)}finally{setBusy(false)}};const file=async(f:File)=>{setBusy(true);setError('');try{const fd=new FormData();fd.append('file',f);const r=await fetch(`${(import.meta as any).env.VITE_API_URL||'http://localhost:4000/api'}/structures/${structureId}/import-file`,{method:'POST',body:fd});const b=await r.json();if(!r.ok)throw new Error(b.error);setBlocks(b.blocks)}catch(e:any){setError(e.message)}finally{setBusy(false)}};const apply=async()=>{setBusy(true);try{await postJson(`/structures/${structureId}/apply-import`,{blocks,mode});onApplied()}catch(e:any){setError(e.message)}finally{setBusy(false)}};return <Modal title="Import report structure" onClose={onClose} width="900px"><div className="importTabs"><button className={tab==='paste'?'active':''} onClick={()=>setTab('paste')}>Paste text</button><button className={tab==='file'?'active':''} onClick={()=>setTab('file')}>Upload or drag file</button></div>{tab==='paste'?<><textarea className="pasteArea" placeholder={'Paste headings and content here.\n1 Institutional Overview\n1.1 Vision and Mission\n- Evidence item'} value={text} onChange={e=>setText(e.target.value)}/><Button onClick={analyseText} disabled={!text.trim()||busy}>Analyse pasted content</Button></>:<label className="fileDrop" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const f=e.dataTransfer.files[0];if(f)file(f)}}><FileUp size={34}/><b>Drop a document here</b><span>DOCX, PDF, XLSX, PPTX, TXT, Markdown, HTML, CSV and RTF</span><input type="file" accept=".docx,.pdf,.xlsx,.pptx,.txt,.md,.html,.htm,.csv,.rtf" onChange={e=>e.target.files?.[0]&&file(e.target.files[0])}/></label>}{error&&<div className="finding error">{error}</div>}{blocks.length>0&&<><div className="importPreview"><h4>Detected elements ({blocks.length})</h4>{blocks.slice(0,100).map((b,i)=><div key={i}><Badge>{b.type}{b.level?` ${b.level}`:''}</Badge><span>{b.text||(b.items||[]).join(', ')||b.caption||'Embedded element'}</span></div>)}</div><label>Import mode<select value={mode} onChange={e=>setMode(e.target.value)}><option value="append">Append to current structure</option><option value="replace">Replace current structure</option></select></label></>}<div className="modalActions"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button onClick={apply} disabled={!blocks.length||busy}>Import {blocks.length} elements</Button></div></Modal>}
function NameModal({title,label,onClose,onCreate}:{title:string;label:string;onClose:any;onCreate:(name:string,description?:string)=>Promise<void>}){const[name,setName]=useState(''),[description,setDescription]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const submit=async(e?:React.FormEvent)=>{e?.preventDefault();const value=name.trim();if(!value||busy)return;setBusy(true);setError('');try{await onCreate(value,description.trim())}catch(err:any){setError(err?.message||'Unable to create project. Please confirm that the API service is running.');setBusy(false)}};return <Modal title={title} onClose={()=>!busy&&onClose()}><form onSubmit={submit} className="nameModalForm"><label>{label}<input autoFocus value={name} maxLength={160} onChange={e=>setName(e.target.value)} placeholder="Enter a clear project name" disabled={busy}/></label>{title.toLowerCase().includes('project')&&<label>Description <span className="optionalText">(optional)</span><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Purpose or scope of this project" disabled={busy}/></label>}{error&&<div className="formError" role="alert">{error}</div>}<div className="modalActions"><Button variant="secondary" onClick={onClose} disabled={busy}>Cancel</Button><Button type="submit" disabled={!name.trim()||busy}>{busy?'Creating…':'Create'}</Button></div></form></Modal>}
function Lines({label,value=[],onChange}:{label:string;value?:string[];onChange:any}){return <label>{label}<textarea value={value.join('\n')} onChange={e=>onChange(e.target.value.split('\n').map(x=>x.trim()).filter(Boolean))}/></label>}
function TableEditor({value,onChange}:{value:string;onChange:any}){let d={columns:['Column 1','Column 2'],rows:[['','']]};try{d=JSON.parse(value||'{}');if(!d.columns)d.columns=['Column 1','Column 2'];if(!d.rows)d.rows=[['','']]}catch{}return <label className="full">Table data<textarea rows={8} value={[d.columns.join(' | '),...d.rows.map((r:string[])=>r.join(' | '))].join('\n')} onChange={e=>{const lines=e.target.value.split('\n');onChange(JSON.stringify({columns:(lines.shift()||'').split('|').map(x=>x.trim()),rows:lines.map(x=>x.split('|').map(y=>y.trim()))}))}}/><small>Use one row per line and separate cells with |.</small></label>}
function preview(e:StructureElement){return (e.content||e.type).slice(0,80)}
